import type { Tool, Article, ToolCategory, Category, UseCase } from './types';
import { content as article1Content } from './articles/ai-girlfriend-companionship-digital-age';
import { content as article2Content } from './articles/ai-video-revolution-sora-pika-runway';
import { content as article3Content } from './articles/ai-agents-autonomous-workforce';
import { NvideaArticle } from './articles/Nvidia-Halts-Reported-$100-Billion-Investment-Plan-in-OpenAI-A-Deep-Dive-into-AI-Industry-Dynamics';
import { OpenClawArticle } from './articles/openclaw-moltbot-viral-phenomenon';
import { OperatorArticle } from './articles/openai-operator-action-era';
import { NerovetArticle } from './articles/nerovet-ai-dental';

const CATEGORIES: Category[] = [
  { slug: 'writing', name: 'Writing', description: 'Tools to assist with writing, editing, and content creation.' },
  { slug: 'image', name: 'Image', description: 'Generate, edit, and enhance images with AI.' },
  { slug: 'video', name: 'Video', description: 'Create and edit videos with AI-powered features.' },
  { slug: 'audio', name: 'Audio', description: 'Tools for audio generation, editing, and transcription.' },
  { slug: 'coding', name: 'Coding', description: 'AI assistants for writing and debugging code.' },
  { slug: 'productivity', name: 'Productivity', description: 'Boost your efficiency and organization.' },
  { slug: 'marketing', name: 'Marketing', description: 'AI tools for marketing, SEO, and social media.' },
  { slug: 'business', name: 'Business', description: 'Solutions for business intelligence and operations.' },
  { slug: 'seo', name: 'SEO', description: 'Optimize your content for search engines.' },
  { slug: 'chatbot', name: 'Chatbot', description: 'Engage with users through conversational AI assistants.' },
  { slug: 'design', name: 'Design', description: 'Create graphics and designs with AI-powered tools.' },
  { slug: 'research', name: 'Research', description: 'AI-powered tools for research and information gathering.' },
  { slug: 'search', name: 'Search', description: 'Next-generation search engines powered by AI.' },
  { slug: 'development', name: 'Development', description: 'Tools and platforms for AI application development.' },
  { slug: 'presentations', name: 'Presentations', description: 'Create compelling presentations with AI assistance.' },
  { slug: 'voice', name: 'Voice', description: 'Tools for voice synthesis and audio manipulation.' },
  { slug: 'music', name: 'Music', description: 'Generate original music and soundscapes with AI.' },
  { slug: 'hosting', name: 'Hosting', description: 'Platforms for deploying and hosting web applications.' },
];

const USE_CASES: UseCase[] = [
  { slug: 'writers', name: 'Writers', description: 'Enhance your writing process and creativity.' },
  { slug: 'students', name: 'Students', description: 'Tools for research, studying, and assignments.' },
  { slug: 'creators', name: 'Creators', description: 'For content creators, artists, and designers.' },
  { slug: 'startups', name: 'Startups', description: 'Scale your business with AI-powered solutions.' },
  { slug: 'developers', name: 'Developers', description: 'Code faster and smarter with AI assistants.' },
];

const tools: Tool[] = [
  {
    id: '1',
    slug: 'chatgpt',
    name: 'ChatGPT',
    description: "OpenAI's conversational AI for writing, coding, analysis, and creative tasks.",
    longDescription: "ChatGPT is a state-of-the-art conversational AI from OpenAI. It can generate human-like text for a variety of applications, from writing emails and essays to coding and answering complex questions. Its versatility makes it an indispensable tool for writers, developers, and students.",
    category: 'Writing',
    trending: true,
    logoUrlId: 'logo-chatgpt',
    website: 'https://chat.openai.com',
    useCases: ['writers', 'developers', 'students', 'creators'],
  },
  {
    id: '2',
    slug: 'claude',
    name: 'Claude',
    description: "Anthropic's AI assistant for analysis, writing, coding, and long-form content.",
    longDescription: "Claude is a next-generation AI assistant from Anthropic, designed to be helpful, harmless, and honest. It specializes in handling long-form content, making it ideal for summarizing large documents, answering questions about complex topics, and collaborative writing.",
    category: 'Writing',
    trending: true,
    logoUrlId: 'logo-claude',
    website: 'https://claude.ai',
    useCases: ['writers', 'research', 'students'],
  },
  {
    id: '3',
    slug: 'jasper-ai',
    name: 'Jasper AI',
    description: 'AI copywriting tool for marketing content, blogs, and social media',
    longDescription: "Jasper AI is a powerful AI writing assistant designed for marketers and content creators. Generate blog posts, ad copy, social media content, and more with advanced AI technology.",
    category: 'Writing',
    logoUrlId: 'logo-jasper-ai',
    website: 'https://www.jasper.ai',
    useCases: ['marketing', 'writers', 'startups'],
  },
  {
    id: '4',
    slug: 'copy-ai',
    name: 'Copy.ai',
    description: 'AI-powered marketing copy and content generation tool',
    longDescription: "Copy.ai helps you create high-quality marketing copy, blog posts, emails, and social media content in seconds using advanced AI writing technology.",
    category: 'Writing',
    logoUrlId: 'logo-copy-ai',
    website: 'https://www.copy.ai',
    useCases: ['marketing', 'writers', 'startups'],
  },
  {
    id: '5',
    slug: 'perplexity-ai',
    name: 'Perplexity AI',
    description: 'AI-powered search engine with cited sources and conversational answers.',
    longDescription: "Perplexity AI is an innovative AI search engine that provides direct, cited answers to questions. It functions as a conversational 'answer engine' by synthesizing information from multiple sources on the web, complete with citations, to deliver trustworthy and accurate results.",
    category: 'Search',
    trending: true,
    logoUrlId: 'logo-perplexity',
    website: 'https://www.perplexity.ai',
    useCases: ['students', 'research', 'writers'],
  },
  {
    id: '6',
    slug: 'midjourney',
    name: 'Midjourney',
    description: 'AI art generator creating stunning images from text prompts.',
    longDescription: "Midjourney is a renowned AI art generator that produces high-quality, artistic images from simple text prompts. Accessed through Discord, it allows users to create stunning visuals in a wide range of styles, making it a favorite among artists, designers, and hobbyists.",
    category: 'Image',
    trending: true,
    logoUrlId: 'logo-midjourney',
    website: 'https://www.midjourney.com',
    useCases: ['creators', 'designers', 'artists'],
  },
  {
    id: '7',
    slug: 'dall-e-3',
    name: 'DALL-E 3',
    description: "OpenAI's advanced text-to-image generation model",
    longDescription: "DALL-E 3 by OpenAI creates highly detailed and accurate images from text descriptions. Available through ChatGPT Plus and the API.",
    category: 'Image',
    logoUrlId: 'logo-dall-e-3',
    website: 'https://openai.com/dall-e-3',
    useCases: ['creators', 'designers', 'artists'],
  },
  {
    id: '8',
    slug: 'canva-ai',
    name: 'Canva AI',
    description: 'Design platform with AI-powered image generation and editing',
    longDescription: "Canva AI combines easy-to-use design tools with powerful AI features like Magic Write, text-to-image, and background removal.",
    category: 'Image',
    logoUrlId: 'logo-canva-ai',
    website: 'https://www.canva.com',
    useCases: ['creators', 'marketing', 'startups'],
  },
  {
    id: '9',
    slug: 'stable-diffusion',
    name: 'Stable Diffusion',
    description: 'Open-source AI image generation model',
    longDescription: "Stable Diffusion is a powerful open-source text-to-image model that runs locally or in the cloud. Create unlimited images with complete creative control.",
    category: 'Image',
    logoUrlId: 'logo-stable-diffusion',
    website: 'https://stability.ai',
    useCases: ['developers', 'creators', 'artists'],
  },
  {
    id: '10',
    slug: 'github-copilot',
    name: 'GitHub Copilot',
    description: 'AI pair programmer that suggests code completions',
    longDescription: "GitHub Copilot is your AI pair programmer powered by OpenAI Codex. Get intelligent code suggestions directly in your editor.",
    category: 'Coding',
    logoUrlId: 'logo-github-copilot',
    website: 'https://github.com/features/copilot',
    useCases: ['developers', 'startups'],
  },
  {
    id: '11',
    slug: 'cursor',
    name: 'Cursor',
    description: 'AI-first code editor built on VS Code with intelligent code generation.',
    longDescription: "Cursor is an AI-first code editor designed for modern software development. Built on VS Code, it offers intelligent code generation, editing, and debugging capabilities, allowing you to build software faster and more efficiently with the help of AI.",
    category: 'Coding',
    trending: true,
    logoUrlId: 'logo-cursor',
    website: 'https://www.cursor.so',
    useCases: ['developers'],
  },
  {
    id: '12',
    slug: 'bolt-new',
    name: 'Bolt.new',
    description: 'AI-powered full-stack web development in the browser by StackBlitz.',
    longDescription: "Bolt.new, from StackBlitz, is an AI-powered tool that enables full-stack web development directly in the browser. It helps you scaffold, build, and deploy web applications with AI assistance, streamlining the development workflow.",
    category: 'Development',
    trending: true,
    logoUrlId: 'logo-bolt-new',
    website: 'https://bolt.new',
    useCases: ['developers', 'startups'],
  },
  {
    id: '13',
    slug: 'v0-by-vercel',
    name: 'v0 by Vercel',
    description: 'AI-powered UI generation tool that creates React components.',
    longDescription: "v0.dev is a generative UI tool by Vercel that creates React components based on text prompts and images. It allows developers to rapidly prototype and build user interfaces using AI, generating production-ready code that can be easily copied and customized.",
    category: 'Development',
    trending: true,
    logoUrlId: 'logo-v0',
    website: 'https://v0.dev',
    useCases: ['developers', 'designers'],
  },
  {
    id: '14',
    slug: 'replit-ai',
    name: 'Replit AI',
    description: 'AI-powered collaborative coding environment',
    longDescription: "Replit AI offers AI-assisted coding with Ghostwriter, instant deployment, and collaborative features all in your browser.",
    category: 'Coding',
    logoUrlId: 'logo-replit-ai',
    website: 'https://replit.com',
    useCases: ['developers', 'students'],
  },
  {
    id: '15',
    slug: 'notion-ai',
    name: 'Notion AI',
    description: 'AI-powered workspace for notes, docs, and project management',
    longDescription: "Notion AI integrates powerful AI features directly into your Notion workspace. Write faster, think bigger, and augment your creativity with AI assistance.",
    category: 'Writing',
    logoUrlId: 'logo-notion-ai',
    website: 'https://www.notion.so',
    useCases: ['students', 'writers', 'startups'],
  },
  {
    id: '16',
    slug: 'gamma',
    name: 'Gamma',
    description: 'AI-powered presentation and document creation',
    longDescription: "Gamma creates beautiful presentations, documents, and webpages in seconds using AI. No design skills required.",
    category: 'Productivity',
    logoUrlId: 'logo-gamma-app',
    website: 'https://gamma.app',
    useCases: ['students', 'startups', 'marketing'],
  },
  {
    id: '17',
    slug: 'descript',
    name: 'Descript',
    description: 'AI-powered audio and video editing with transcription',
    longDescription: "Descript edits audio and video like a document. Remove filler words, enhance audio quality, and create AI voices.",
    category: 'Audio',
    logoUrlId: 'logo-descript-audio',
    website: 'https://www.descript.com',
    useCases: ['creators', 'podcasters', 'video-editors'],
  },
  {
    id: '18',
    slug: 'google-ai-studio',
    name: 'Google AI Studio',
    description: "Google's platform for experimenting with Gemini models.",
    longDescription: "Google AI Studio is a web-based platform that allows developers to experiment with and prototype using Google's latest Gemini models. It provides a user-friendly interface to test prompts and explore the capabilities of Google's powerful AI.",
    category: 'Development',
    logoUrlId: 'logo-google-ai',
    website: 'https://aistudio.google.com',
    useCases: ['developers', 'research'],
  },
  {
    id: '19',
    slug: 'hugging-face',
    name: 'Hugging Face',
    description: 'Platform for building, training, and deploying ML models.',
    longDescription: "Hugging Face is the leading open-source platform for machine learning. It provides a vast repository of pre-trained models, datasets, and tools, enabling developers and researchers to build, train, and deploy state-of-the-art AI applications.",
    category: 'Development',
    logoUrlId: 'logo-hugging-face',
    website: 'https://huggingface.co',
    useCases: ['developers', 'research'],
  },
  {
    id: '20',
    slug: 'vercel',
    name: 'Vercel',
    description: 'Frontend deployment platform with AI features.',
    longDescription: "Vercel is a premier frontend deployment platform optimized for Next.js and other modern frameworks. It offers a seamless development and deployment experience, with integrated AI features to enhance developer productivity and site performance.",
    category: 'Hosting',
    logoUrlId: 'logo-vercel',
    website: 'https://vercel.com',
    useCases: ['developers', 'startups'],
  },
  {
    id: '21',
    slug: 'netlify',
    name: 'Netlify',
    description: 'Web development platform with AI-powered features.',
    longDescription: "Netlify is a powerful web development platform for building and deploying fast, modern websites and applications. It provides a git-based workflow, serverless functions, and a growing suite of AI-powered features to simplify web development.",
    category: 'Hosting',
    logoUrlId: 'logo-netlify',
    website: 'https://www.netlify.com',
    useCases: ['developers', 'startups'],
  },
  {
    id: '22',
    slug: 'runway',
    name: 'Runway',
    description: 'AI-powered video editing and generation tools.',
    longDescription: "Runway offers a suite of powerful AI-powered tools for video and image creation and editing. From text-to-video generation to advanced motion tracking and green screen removal, Runway is a comprehensive platform for creative professionals.",
    category: 'Video',
    logoUrlId: 'logo-runwayml',
    website: 'https://runwayml.com',
    useCases: ['creators', 'video-editors', 'designers'],
  },
  {
    id: '23',
    slug: 'elevenlabs',
    name: 'ElevenLabs',
    description: 'AI voice generation and text-to-speech with realistic voices',
    longDescription: "ElevenLabs creates ultra-realistic AI voices for text-to-speech, voice cloning, and dubbing in 29 languages.",
    category: 'Audio',
    logoUrlId: 'logo-elevenlabs',
    website: 'https://elevenlabs.io',
    useCases: ['creators', 'podcasters', 'developers'],
  },
  {
    id: '24',
    slug: 'suno',
    name: 'Suno',
    description: 'AI music generation from text prompts.',
    longDescription: "Suno is an AI music generation tool that creates original songs, complete with vocals and instrumentation, from simple text prompts. It empowers anyone to create radio-quality music in any genre, regardless of their musical ability.",
    category: 'Music',
    trending: true,
    logoUrlId: 'logo-suno',
    website: 'https://www.suno.ai',
    useCases: ['creators', 'musicians', 'developers'],
  },
  {
    id: '25',
    slug: 'udio',
    name: 'Udio',
    description: 'AI music generator with advanced control over song structure and style.',
    longDescription: 'Udio is an advanced AI music creation platform that generates high-quality songs with precise control over genres, moods, and song structure. Created by former Google DeepMind researchers.',
    category: 'Music',
    trending: false,
    logoUrlId: 'logo-udio',
    website: 'https://udio.com',
    useCases: ['creators'],
  },
  {
    id: '26',
    slug: 'mubert',
    name: 'Mubert',
    description: 'AI-generated royalty-free music for content creators and businesses.',
    longDescription: 'Mubert generates unique, royalty-free music in real-time using AI. Perfect for content creators, streamers, podcasters, and businesses needing background music.',
    category: 'Music',
    trending: false,
    logoUrlId: 'logo-mubert',
    website: 'https://mubert.com',
    useCases: ['creators', 'startups'],
  },
  {
    id: '27',
    slug: 'soundraw',
    name: 'Soundraw',
    description: 'AI music generator with customizable tracks for creators.',
    longDescription: 'Soundraw lets you generate unlimited royalty-free music and customize it to fit your content perfectly. Adjust length, tempo, instruments, and energy levels.',
    category: 'Music',
    trending: false,
    logoUrlId: 'logo-soundraw',
    website: 'https://soundraw.io',
    useCases: ['creators'],
  },
  {
    id: '28',
    slug: 'boomy',
    name: 'Boomy',
    description: 'Create songs in seconds and release them to streaming platforms.',
    longDescription: 'Boomy enables anyone to create original songs in seconds and release them on Spotify, Apple Music, and other platforms. Earn royalties from your AI-generated music.',
    category: 'Music',
    trending: false,
    logoUrlId: 'logo-boomy',
    website: 'https://boomy.com',
    useCases: ['creators', 'startups'],
  },
  {
    id: '29',
    slug: 'aiva',
    name: 'AIVA',
    description: 'AI music composition tool for professional soundtracks and scores.',
    longDescription: 'AIVA is an AI composer that creates original music for films, video games, commercials, and other professional projects. Recognized as the first virtual artist by SACEM.',
    category: 'Music',
    trending: false,
    logoUrlId: 'logo-aiva',
    website: 'https://aiva.ai',
    useCases: ['creators', 'developers'],
  },
  {
    id: '30',
    slug: 'beatoven-ai',
    name: 'Beatoven.ai',
    description: 'AI music generator that creates mood-based soundtracks for videos.',
    longDescription: 'Beatoven.ai generates customizable, royalty-free music that adapts to your video\'s mood and pacing. Perfect for content creators and marketers.',
    category: 'Music',
    trending: false,
    logoUrlId: 'logo-beatoven-ai',
    website: 'https://beatoven.ai',
    useCases: ['creators'],
  },
  {
    id: '31',
    slug: 'loudly',
    name: 'Loudly',
    description: 'AI music platform for creating, customizing, and licensing music.',
    longDescription: 'Loudly is an AI-powered music platform that lets you generate, customize, and license original music for commercial use. Features a vast library of sounds and stems.',
    category: 'Music',
    trending: false,
    logoUrlId: 'logo-loudly',
    website: 'https://loudly.com',
    useCases: ['creators', 'startups'],
  },
  {
    id: '32',
    slug: 'splash-pro',
    name: 'Splash Pro',
    description: 'AI music creation with vocals, rap, and singing capabilities.',
    longDescription: 'Splash Pro is an AI music platform that generates songs with vocals, including rap and singing. Create full tracks with lyrics and melodies from text prompts.',
    category: 'Music',
    trending: false,
    logoUrlId: 'logo-splash-pro',
    website: 'https://www.splashmusic.com',
    useCases: ['creators'],
  },
  {
    id: '33',
    slug: 'soundful',
    name: 'Soundful',
    description: 'AI music generator for creators, brands, and artists.',
    longDescription: 'Soundful is an AI music platform that creates unique, royalty-free tracks at the click of a button. Choose from genres, moods, and customize to your needs.',
    category: 'Music',
    trending: false,
    logoUrlId: 'logo-soundful',
    website: 'https://soundful.com',
    useCases: ['creators', 'startups'],
  },
  {
    id: '34',
    slug: 'amper-music',
    name: 'Amper Music',
    description: 'AI music composition integrated with Shutterstock.',
    longDescription: 'Amper Music (now part of Shutterstock) creates custom AI-generated music for content creators. Simple interface for creating professional soundtracks.',
    category: 'Music',
    trending: false,
    logoUrlId: 'logo-amper-music',
    website: 'https://www.shutterstock.com/discover/ampermusic',
    useCases: ['creators'],
  },
  {
    id: '35',
    slug: 'ecrett-music',
    name: 'Ecrett Music',
    description: 'AI music generator for video and game creators.',
    longDescription: 'Ecrett Music generates royalty-free music based on scene, mood, and genre. Perfect for video creators, game developers, and content makers.',
    category: 'Music',
    trending: false,
    logoUrlId: 'logo-ecrett-music',
    website: 'https://ecrettmusic.com',
    useCases: ['creators', 'developers'],
  },
  {
    id: '36',
    slug: 'riffusion',
    name: 'Riffusion',
    description: 'Real-time music generation using stable diffusion.',
    longDescription: 'Riffusion generates music in real-time using stable diffusion. Create unique instrumentals and experiment with different styles and genres.',
    category: 'Music',
    trending: false,
    logoUrlId: 'logo-riffusion',
    website: 'https://riffusion.com',
    useCases: ['developers', 'creators'],
  },
  {
    id: '37',
    slug: 'songburst',
    name: 'Songburst',
    description: 'AI music generator for creating original songs from text descriptions.',
    longDescription: 'Songburst creates original songs from your text prompts. Describe the song you want and get an AI-generated track in seconds.',
    category: 'Music',
    trending: false,
    logoUrlId: 'logo-songburst',
    website: 'https://www.songburst.ai',
    useCases: ['creators'],
  },
  {
    id: '38',
    slug: 'wavtool',
    name: 'WavTool',
    description: 'Browser-based AI music production studio with AI assistance.',
    longDescription: 'WavTool is a browser-based music production tool with AI-powered features for composition, mixing, and mastering. No downloads required.',
    category: 'Music',
    trending: false,
    logoUrlId: 'logo-wavtool',
    website: 'https://wavtool.com',
    useCases: ['creators', 'developers'],
  },
  {
    id: '39',
    slug: 'stable-audio',
    name: 'Stable Audio',
    description: 'High-quality AI audio generation by Stability AI.',
    longDescription: 'Stable Audio by Stability AI generates high-quality music and sound effects from text descriptions. Professional-grade audio for creators and developers.',
    category: 'Audio',
    trending: false,
    logoUrlId: 'logo-stable-audio',
    website: 'https://stableaudio.com',
    useCases: ['creators', 'developers'],
  },
  {
    id: '40',
    slug: 'soundverse',
    name: 'Soundverse',
    description: 'AI music assistant for creators with voice commands.',
    longDescription: 'Soundverse is an AI music assistant that helps you create music using voice commands and text prompts. Generate stems, loops, and full tracks effortlessly.',
    category: 'Music',
    trending: false,
    logoUrlId: 'logo-soundverse',
    website: 'https://soundverse.ai',
    useCases: ['creators', 'developers'],
  },
  {
    id: '41',
    slug: 'harmonai',
    name: 'Harmonai',
    description: 'Open-source AI music generation community and tools.',
    longDescription: 'Harmonai is a community-driven organization releasing open-source generative audio tools. Create music with cutting-edge AI models available to everyone.',
    category: 'Music',
    trending: false,
    logoUrlId: 'logo-harmonai',
    website: 'https://www.harmonai.org',
    useCases: ['developers'],
  },
  {
    id: '42',
    slug: 'amadeus-code',
    name: 'Amadeus Code',
    description: 'AI songwriting assistant powered by hit songs.',
    longDescription: 'Amadeus Code uses AI trained on hit songs to help you create melodies and chord progressions. Perfect for songwriters seeking inspiration.',
    category: 'Music',
    trending: false,
    logoUrlId: 'logo-amadeus-code',
    website: 'https://amadeuscode.com/',
    useCases: ['creators'],
  },
  {
    id: '43',
    slug: 'musicfy',
    name: 'Musicfy',
    description: 'AI voice cloning and music generation platform.',
    longDescription: 'Musicfy lets you create AI voice clones and generate music covers with any voice. Clone your voice or use celebrity voices for your tracks.',
    category: 'Voice',
    trending: false,
    logoUrlId: 'logo-musicfy',
    website: 'https://musicfy.lol',
    useCases: ['creators'],
  },
  {
    id: '44',
    slug: 'synthesia',
    name: 'Synthesia',
    description: 'AI video generation with realistic avatars and voiceovers',
    longDescription: 'Synthesia creates professional videos with AI avatars in 120+ languages. Transform text into engaging video presentations without cameras or actors.',
    category: 'Video',
    logoUrlId: 'logo-synthesia',
    website: 'https://www.synthesia.io',
    useCases: ['creators', 'startups'],
  },
  {
    id: '45',
    slug: 'heygen',
    name: 'HeyGen',
    description: 'AI video generator with customizable avatars and voice cloning',
    longDescription: 'HeyGen lets you create studio-quality videos with AI avatars, voice cloning, and automatic translations. Perfect for marketing, training, and social media.',
    category: 'Video',
    logoUrlId: 'logo-heygen',
    website: 'https://www.heygen.com',
    useCases: ['creators', 'startups'],
  },
  {
    id: '46',
    slug: 'pictory',
    name: 'Pictory',
    description: 'Turn scripts and articles into engaging videos automatically',
    longDescription: 'Pictory converts long-form content into short, branded videos perfect for social media. Automatically extract highlights from Zoom recordings and webinars.',
    category: 'Video',
    logoUrlId: 'logo-pictory',
    website: 'https://pictory.ai',
    useCases: ['creators', 'startups'],
  },
  {
    id: '47',
    slug: 'invideo-ai',
    name: 'Invideo AI',
    description: 'AI video creator that turns text prompts into complete videos',
    longDescription: 'Invideo AI generates complete videos from simple text prompts. Create YouTube videos, social media content, and ads with AI-powered editing and scripting.',
    category: 'Video',
    logoUrlId: 'logo-invideo-ai',
    website: 'https://invideo.io',
    useCases: ['creators', 'startups'],
  },
  {
    id: '48',
    slug: 'pika',
    name: 'Pika',
    description: 'AI video generator that creates and edits videos from text',
    longDescription: 'Pika is an AI video platform that generates videos from text descriptions and images. Modify videos with simple text commands for creative control.',
    category: 'Video',
    logoUrlId: 'logo-pika',
    website: 'https://pika.art',
    useCases: ['creators'],
  },
  {
    id: '49',
    slug: 'luma-dream-machine',
    name: 'Luma Dream Machine',
    description: 'High-quality AI video generation from text and images',
    longDescription: 'Luma Dream Machine creates cinematic, high-quality videos from text prompts and images. Known for realistic motion and smooth transitions.',
    category: 'Video',
    logoUrlId: 'logo-luma-dream-machine',
    website: 'https://lumalabs.ai',
    useCases: ['creators'],
  },
  {
    id: '50',
    slug: 'kling-ai',
    name: 'Kling AI',
    description: 'Advanced AI video generation with long-duration support',
    longDescription: 'Kling AI generates high-quality videos up to 2 minutes long with realistic physics and motion. Create stunning visuals from text descriptions.',
    category: 'Video',
    logoUrlId: 'logo-kling-ai',
    website: 'https://klingai.com',
    useCases: ['creators'],
  },
  {
    id: '51',
    slug: 'fliki',
    name: 'Fliki',
    description: 'Text-to-video and text-to-speech for content creators',
    longDescription: 'Fliki converts text into videos with realistic voiceovers in minutes. Create social media content, product demos, and educational videos effortlessly.',
    category: 'Video',
    logoUrlId: 'logo-fliki',
    website: 'https://fliki.ai',
    useCases: ['creators'],
  },
  {
    id: '52',
    slug: 'colossyan',
    name: 'Colossyan',
    description: 'AI video platform for workplace learning and training',
    longDescription: 'Colossyan creates professional training videos with AI avatars and automatic translations. Perfect for corporate learning and employee onboarding.',
    category: 'Video',
    logoUrlId: 'logo-colossyan',
    website: 'https://www.colossyan.com',
    useCases: ['startups'],
  },
  {
    id: '53',
    slug: 'elai-io',
    name: 'Elai.io',
    description: 'AI video generator for training and explainer videos',
    longDescription: 'Elai.io creates professional videos from text with AI presenters. Ideal for training content, explainer videos, and educational material.',
    category: 'Video',
    logoUrlId: 'logo-elai-io',
    website: 'https://elai.io',
    useCases: ['startups', 'students'],
  },
  {
    id: '54',
    slug: 'steve-ai',
    name: 'Steve.AI',
    description: 'AI video maker for animations and live-action videos',
    longDescription: 'Steve.AI creates animated and live-action videos from scripts. Choose from various styles including cartoon, 2D/3D animation, and live video.',
    category: 'Video',
    logoUrlId: 'logo-steve-ai',
    website: 'https://steve.ai',
    useCases: ['creators'],
  },
  {
    id: '55',
    slug: 'deepbrain-ai',
    name: 'Deepbrain AI',
    description: 'Hyper-realistic AI avatar video generation platform',
    longDescription: 'Deepbrain AI (AI Studios) creates videos with hyper-realistic AI avatars. Generate professional video content in multiple languages with natural gestures.',
    category: 'Video',
    logoUrlId: 'logo-deepbrain-ai',
    website: 'https://www.deepbrain.io',
    useCases: ['startups'],
  },
  {
    id: '57',
    slug: 'moonvalley',
    name: 'Moonvalley',
    description: 'AI video generation with artistic styles and control',
    longDescription: 'Moonvalley creates stunning videos from text with various artistic styles. Generate cinematic, animated, or realistic videos with style control.',
    category: 'Video',
    logoUrlId: 'logo-moonvalley',
    website: 'https://moonvalley.ai',
    useCases: ['creators'],
  },
  {
    id: '58',
    slug: 'artflow-ai',
    name: 'Artflow AI',
    description: 'Create animated videos with consistent AI characters',
    longDescription: 'Artflow AI lets you create videos with consistent AI-generated characters. Design your characters and animate them in various scenes and scenarios.',
    category: 'Video',
    logoUrlId: 'logo-artflow-ai',
    website: 'https://artflow.ai',
    useCases: ['creators'],
  },
  {
    id: '59',
    slug: 'opusclip',
    name: 'OpusClip',
    description: 'AI-powered video clipping for social media shorts',
    longDescription: 'OpusClip automatically identifies viral-worthy moments in long videos and creates short clips perfect for TikTok, YouTube Shorts, and Instagram Reels.',
    category: 'Video',
    logoUrlId: 'logo-opusclip',
    website: 'https://www.opus.pro',
    useCases: ['creators'],
  },
  {
    id: '60',
    slug: 'vidyo-ai',
    name: 'Vidyo.ai',
    description: 'Repurpose long videos into social media shorts with AI',
    longDescription: 'Vidyo.ai automatically turns long-form videos into short, engaging clips for social media. AI identifies the best moments and adds captions automatically.',
    category: 'Video',
    logoUrlId: 'logo-vidyo-ai',
    website: 'https://vidyo.ai',
    useCases: ['creators'],
  },
  {
    id: '61',
    slug: 'kapwing',
    name: 'Kapwing',
    description: 'Collaborative online video editor with AI features',
    longDescription: 'Kapwing is an online video editor with AI-powered tools for subtitles, resizing, background removal, and more. Perfect for teams and content creators.',
    category: 'Video',
    logoUrlId: 'logo-kapwing',
    website: 'https://www.kapwing.com',
    useCases: ['creators', 'startups'],
  },
  {
    id: '62',
    slug: 'animoto',
    name: 'Animoto',
    description: 'AI video maker for marketing and social media',
    longDescription: 'Animoto creates professional marketing videos with AI assistance. Drag-and-drop editor with templates for social media, ads, and presentations.',
    category: 'Video',
    logoUrlId: 'logo-animoto',
    website: 'https://animoto.com',
    useCases: ['creators'],
  },
  {
    id: '63',
    slug: 'clipchamp',
    name: 'Clipchamp',
    description: "Microsoft's AI-powered video editor for everyone",
    longDescription: "Clipchamp (by Microsoft) offers easy video editing with AI features like auto-captions, text-to-speech, and templates. Built into Windows 11.",
    category: 'Video',
    logoUrlId: 'logo-clipchamp',
    website: 'https://clipchamp.com',
    useCases: ['creators'],
  },
  {
    id: '64',
    slug: 'captions-app',
    name: 'Captions',
    description: 'AI-powered video editing and captioning for creators',
    longDescription: 'Captions automatically adds animated captions to your videos, corrects eye contact with AI, and enhances video quality. Perfect for social media creators.',
    category: 'Video',
    logoUrlId: 'logo-captions-app',
    website: 'https://www.captions.ai',
    useCases: ['creators'],
  },
  {
    id: '65',
    slug: 'kaiber',
    name: 'Kaiber',
    description: 'Transform videos and images with AI artistic styles',
    longDescription: 'Kaiber transforms your videos and images into artistic animations. Apply different visual styles to create unique music videos and artistic content.',
    category: 'Video',
    logoUrlId: 'logo-kaiber',
    website: 'https://kaiber.ai',
    useCases: ['creators'],
  },
  {
    id: '66',
    slug: 'wonder-studio',
    name: 'Wonder Studio',
    description: 'AI tool for adding CG characters to live-action footage',
    longDescription: 'Wonder Studio automatically animates, lights, and composes CG characters into live-action scenes. Revolutionary tool for filmmakers and VFX artists.',
    category: 'Video',
    logoUrlId: 'logo-wonder-studio',
    website: 'https://wonderdynamics.com',
    useCases: ['creators', 'developers'],
  },
  {
    id: '67',
    slug: 'd-id',
    name: 'D-ID',
    description: 'AI video platform with talking avatars and face animation',
    longDescription: 'D-ID creates videos with talking avatars from still images. Generate personalized video content with AI-powered facial animation and voice.',
    category: 'Video',
    logoUrlId: 'logo-d-id',
    website: 'https://www.d-id.com',
    useCases: ['creators'],
  },
  {
    id: '68',
    slug: 'lumen5',
    name: 'Lumen5',
    description: 'AI video creator that transforms blog posts into videos',
    longDescription: 'Lumen5 automatically converts blog posts and articles into engaging videos. AI selects relevant media and creates professional social media content.',
    category: 'Video',
    logoUrlId: 'logo-lumen5',
    website: 'https://lumen5.com',
    useCases: ['creators'],
  },
  {
    id: '69',
    slug: 'writesonic',
    name: 'Writesonic',
    description: 'AI writer for articles, blog posts, and marketing copy',
    longDescription: 'Writesonic is an AI content creation platform that helps you write SEO-optimized articles, blog posts, ads, landing pages, and more in minutes.',
    category: 'Writing',
    trending: false,
    logoUrlId: 'logo-writesonic',
    website: 'https://writesonic.com',
    useCases: [],
  },
  {
    id: '70',
    slug: 'grammarly',
    name: 'Grammarly',
    description: 'AI-powered writing assistant for grammar, spelling, and clarity',
    longDescription: 'Grammarly uses AI to help you write mistake-free content with suggestions for grammar, spelling, punctuation, clarity, and tone across all your apps.',
    category: 'Writing',
    trending: false,
    logoUrlId: 'logo-grammarly',
    website: 'https://www.grammarly.com',
    useCases: [],
  },
  {
    id: '71',
    slug: 'quillbot',
    name: 'QuillBot',
    description: 'AI paraphrasing and writing enhancement tool',
    longDescription: 'QuillBot is an AI-powered paraphrasing tool that helps you rewrite content, improve clarity, check grammar, and enhance your writing style.',
    category: 'Writing',
    trending: false,
    logoUrlId: 'logo-quillbot',
    website: 'https://quillbot.com',
    useCases: [],
  },
  {
    id: '72',
    slug: 'rytr',
    name: 'Rytr',
    description: 'Affordable AI writing assistant for content creation',
    longDescription: 'Rytr is an AI writing assistant that helps you create high-quality content quickly and affordably. Generate blog posts, emails, ads, and more in 30+ languages.',
    category: 'Writing',
    trending: false,
    logoUrlId: 'logo-rytr',
    website: 'https://rytr.me',
    useCases: [],
  },
  {
    id: '73',
    slug: 'wordtune',
    name: 'Wordtune',
    description: 'AI writing companion that helps you say exactly what you mean',
    longDescription: 'Wordtune is an AI-powered writing tool that helps you rewrite and rephrase sentences to be clearer, more engaging, and better suited to your audience.',
    category: 'Writing',
    trending: false,
    logoUrlId: 'logo-wordtune',
    website: 'https://www.wordtune.com',
    useCases: [],
  },
  {
    id: '74',
    slug: 'sudowrite',
    name: 'Sudowrite',
    description: 'AI writing tool designed specifically for creative fiction writers',
    longDescription: "Sudowrite is an AI writing partner for fiction authors. Get help with brainstorming, description, character development, and overcoming writer's block.",
    category: 'Writing',
    trending: false,
    logoUrlId: 'logo-sudowrite',
    website: 'https://www.sudowrite.com',
    useCases: [],
  },
  {
    id: '75',
    slug: 'hemingway-editor',
    name: 'Hemingway Editor',
    description: 'AI-powered editor that makes your writing bold and clear',
    longDescription: 'Hemingway Editor uses AI to highlight complex sentences, passive voice, and common errors to help you write with clarity and confidence.',
    category: 'Writing',
    trending: false,
    logoUrlId: 'logo-hemingway-editor',
    website: 'https://hemingwayapp.com',
    useCases: [],
  },
  {
    id: '76',
    slug: 'prowritingaid',
    name: 'ProWritingAid',
    description: 'AI writing assistant and editing tool for authors and professionals',
    longDescription: 'ProWritingAid combines AI-powered grammar checking, style editing, and writing reports to help you improve your writing craft and polish your work.',
    category: 'Writing',
    trending: false,
    logoUrlId: 'logo-prowritingaid',
    website: 'https://prowritingaid.com',
    useCases: [],
  },
  {
    id: '77',
    slug: 'simplified',
    name: 'Simplified',
    description: 'All-in-one AI app for content creation and design',
    longDescription: 'Simplified combines AI writing, graphic design, video editing, and social media management in one platform. Create content faster with AI-powered tools.',
    category: 'Writing',
    trending: false,
    logoUrlId: 'logo-simplified',
    website: 'https://simplified.com',
    useCases: [],
  },
  {
    id: '78',
    slug: 'hypotenuse-ai',
    name: 'Hypotenuse AI',
    description: 'AI writing assistant for e-commerce product descriptions and content',
    longDescription: 'Hypotenuse AI specializes in creating product descriptions, blog articles, and marketing copy for e-commerce businesses at scale.',
    category: 'Writing',
    trending: false,
    logoUrlId: 'logo-hypotenuse-ai',
    website: 'https://www.hypotenuse.ai',
    useCases: [],
  },
  {
    id: '79',
    slug: 'longshot-ai',
    name: 'Longshot AI',
    description: 'AI writing assistant for long-form content and SEO blogs',
    longDescription: 'Longshot AI helps you research, generate, and optimize long-form content that ranks. Perfect for bloggers and content marketers focused on SEO.',
    category: 'Writing',
    trending: false,
    logoUrlId: 'logo-longshot-ai',
    website: 'https://www.longshot.ai',
    useCases: [],
  },
  {
    id: '80',
    slug: 'frase',
    name: 'Frase',
    description: 'AI-powered SEO content optimization and research tool',
    longDescription: 'Frase helps you research, write, and optimize SEO content in minutes. Analyze top search results and create content briefs powered by AI.',
    category: 'Writing',
    trending: false,
    logoUrlId: 'logo-frase',
    website: 'https://www.frase.io',
    useCases: [],
  },
  {
    id: '81',
    slug: 'leonardo-ai',
    name: 'Leonardo AI',
    description: 'AI art generator for game assets and creative projects',
    longDescription: 'Leonardo AI creates production-quality visual assets for creative projects. Perfect for game developers, designers, and digital artists.',
    category: 'Image',
    trending: false,
    logoUrlId: 'logo-leonardo-ai',
    website: 'https://leonardo.ai',
    useCases: [],
  },
  {
    id: '82',
    slug: 'adobe-firefly',
    name: 'Adobe Firefly',
    description: "Adobe's AI-powered creative tools for image generation",
    longDescription: "Adobe Firefly brings generative AI into Adobe's creative apps. Generate images, apply styles, and edit photos with AI assistance.",
    category: 'Image',
    trending: false,
    logoUrlId: 'logo-adobe-firefly',
    website: 'https://firefly.adobe.com',
    useCases: [],
  },
  {
    id: '83',
    slug: 'artbreeder',
    name: 'Artbreeder',
    description: 'Collaborative AI art tool for creating characters and landscapes',
    longDescription: 'Artbreeder lets you create and remix images using AI. Perfect for character design, landscapes, and artistic exploration.',
    category: 'Image',
    trending: false,
    logoUrlId: 'logo-artbreeder',
    website: 'https://www.artbreeder.com',
    useCases: [],
  },
  {
    id: '84',
    slug: 'playground-ai',
    name: 'Playground AI',
    description: 'Free AI image generator with editing capabilities',
    longDescription: 'Playground AI offers free AI image generation with powerful editing tools. Create, edit, and enhance images with an intuitive interface.',
    category: 'Image',
    trending: false,
    logoUrlId: 'logo-playground-ai',
    website: 'https://playgroundai.com',
    useCases: [],
  },
  {
    id: '85',
    slug: 'craiyon',
    name: 'Craiyon',
    description: 'Free AI image generator accessible to everyone',
    longDescription: 'Craiyon (formerly DALL-E mini) is a free AI image generator that lets anyone create images from text descriptions without signing up.',
    category: 'Image',
    trending: false,
    logoUrlId: 'logo-craiyon',
    website: 'https://www.craiyon.com',
    useCases: [],
  },
  {
    id: '86',
    slug: 'nightcafe',
    name: 'NightCafe',
    description: 'AI art generator with multiple algorithms and styles',
    longDescription: 'NightCafe offers multiple AI art generation algorithms including Stable Diffusion, DALL-E, and more. Create stunning artwork with various styles.',
    category: 'Image',
    trending: false,
    logoUrlId: 'logo-nightcafe',
    website: 'https://nightcafe.studio',
    useCases: [],
  },
  {
    id: '87',
    slug: 'shutterstock-ai',
    name: 'Shutterstock AI',
    description: 'AI image generation integrated with Shutterstock library',
    longDescription: "Shutterstock AI generates custom images and integrates seamlessly with Shutterstock's vast library of stock photos and assets.",
    category: 'Image',
    trending: false,
    logoUrlId: 'logo-shutterstock-ai',
    website: 'https://www.shutterstock.com/ai-image-generator',
    useCases: [],
  },
  {
    id: '88',
    slug: 'photoshop-ai',
    name: 'Photoshop AI',
    description: 'AI-powered editing tools in Adobe Photoshop',
    longDescription: 'Photoshop AI includes Generative Fill and other AI features that revolutionize photo editing with intelligent content-aware tools.',
    category: 'Image',
    trending: false,
    logoUrlId: 'logo-photoshop-ai',
    website: 'https://www.adobe.com/products/photoshop.html',
    useCases: [],
  },
  {
    id: '89',
    slug: 'fotor-ai',
    name: 'Fotor AI',
    description: 'AI photo editor and image generator',
    longDescription: 'Fotor AI combines photo editing with AI image generation. Enhance photos, remove backgrounds, and create AI art all in one platform.',
    category: 'Image',
    trending: false,
    logoUrlId: 'logo-fotor-ai',
    website: 'https://www.fotor.com',
    useCases: [],
  },
  {
    id: '90',
    slug: 'pixlr-ai',
    name: 'Pixlr AI',
    description: 'Online photo editor with AI-powered features',
    longDescription: 'Pixlr AI offers powerful photo editing with AI features like background removal, object removal, and smart enhancement tools.',
    category: 'Image',
    trending: false,
    logoUrlId: 'logo-pixlr-ai',
    website: 'https://pixlr.com',
    useCases: [],
  },
  {
    id: '91',
    slug: 'dreamstudio',
    name: 'DreamStudio',
    description: 'Official Stable Diffusion interface by Stability AI',
    longDescription: 'DreamStudio is the official interface for Stable Diffusion by Stability AI. Generate high-quality images with advanced control options.',
    category: 'Image',
    trending: false,
    logoUrlId: 'logo-dreamstudio',
    website: 'https://dreamstudio.ai',
    useCases: [],
  },
  {
    id: '92',
    slug: 'ideogram',
    name: 'Ideogram',
    description: 'AI image generator with excellent text rendering',
    longDescription: 'Ideogram specializes in generating images with accurate text rendering, making it perfect for logos, posters, and designs with typography.',
    category: 'Image',
    trending: false,
    logoUrlId: 'logo-ideogram',
    website: 'https://ideogram.ai',
    useCases: [],
  },
  {
    id: '93',
    slug: 'resemble-ai',
    name: 'Resemble AI',
    description: 'AI voice cloning and text-to-speech platform',
    longDescription: 'Resemble AI offers professional voice cloning and text-to-speech for developers, content creators, and enterprises.',
    category: 'Audio',
    trending: false,
    logoUrlId: 'logo-resemble-ai',
    website: 'https://www.resemble.ai',
    useCases: [],
  },
  {
    id: '94',
    slug: 'murf-ai',
    name: 'Murf AI',
    description: 'AI voice generator for professional voiceovers',
    longDescription: 'Murf AI creates studio-quality voiceovers with realistic AI voices. Perfect for videos, presentations, and podcasts.',
    category: 'Audio',
    trending: false,
    logoUrlId: 'logo-murf-ai',
    website: 'https://murf.ai',
    useCases: [],
  },
  {
    id: '95',
    slug: 'play-ht',
    name: 'Play.ht',
    description: 'AI text-to-speech and voice cloning platform',
    longDescription: 'Play.ht converts text to natural-sounding audio with ultra-realistic AI voices in 142 languages.',
    category: 'Audio',
    trending: false,
    logoUrlId: 'logo-play-ht',
    website: 'https://play.ht',
    useCases: [],
  },
  {
    id: '96',
    slug: 'speechify',
    name: 'Speechify',
    description: 'AI text-to-speech for reading documents and articles',
    longDescription: 'Speechify reads any text aloud with natural-sounding AI voices. Perfect for productivity, learning, and accessibility.',
    category: 'Audio',
    trending: false,
    logoUrlId: 'logo-speechify',
    website: 'https://speechify.com',
    useCases: [],
  },
  {
    id: '97',
    slug: 'voicemod',
    name: 'Voicemod',
    description: 'Real-time AI voice changer for gaming and content creation',
    longDescription: 'Voicemod is a real-time voice changer with AI-powered voice effects for gamers, streamers, and content creators.',
    category: 'Audio',
    trending: false,
    logoUrlId: 'logo-voicemod',
    website: 'https://www.voicemod.net',
    useCases: [],
  },
  {
    id: '98',
    slug: 'adobe-podcast-ai',
    name: 'Adobe Podcast AI',
    description: 'AI-powered audio recording and editing for podcasts',
    longDescription: 'Adobe Podcast AI enhances audio quality, removes background noise, and provides professional editing tools for podcasters.',
    category: 'Audio',
    trending: false,
    logoUrlId: 'logo-adobe-podcast-ai',
    website: 'https://podcast.adobe.com',
    useCases: [],
  },
  {
    id: '99',
    slug: 'krisp',
    name: 'Krisp',
    description: 'AI noise cancellation for calls and recordings',
    longDescription: 'Krisp removes background noise and echo from audio in real-time. Perfect for remote work, podcasting, and content creation.',
    category: 'Audio',
    trending: false,
    logoUrlId: 'logo-krisp',
    website: 'https://krisp.ai',
    useCases: [],
  },
  {
    id: '100',
    slug: 'podcastle',
    name: 'Podcastle',
    description: 'AI-powered podcast recording and editing platform',
    longDescription: 'Podcastle offers studio-quality podcast recording, editing, and AI-powered audio enhancement in one platform.',
    category: 'Audio',
    trending: false,
    logoUrlId: 'logo-podcastle',
    website: 'https://podcastle.ai',
    useCases: [],
  },
  {
    id: '101',
    slug: 'cleanvoice-ai',
    name: 'Cleanvoice AI',
    description: 'AI audio editing to remove filler words and silence',
    longDescription: 'Cleanvoice AI automatically removes filler words, mouth sounds, and long silences from podcast and audio recordings.',
    category: 'Audio',
    trending: false,
    logoUrlId: 'logo-cleanvoice-ai',
    website: 'https://cleanvoice.ai',
    useCases: [],
  },
  {
    id: '102',
    slug: 'auphonic',
    name: 'Auphonic',
    description: 'Automatic audio post-production and enhancement',
    longDescription: 'Auphonic automatically improves audio quality with intelligent leveling, noise reduction, and loudness normalization.',
    category: 'Audio',
    trending: false,
    logoUrlId: 'logo-auphonic',
    website: 'https://auphonic.com',
    useCases: [],
  },
  {
    id: '103',
    slug: 'lalal-ai',
    name: 'Lalal.ai',
    description: 'AI-powered vocal and instrumental track separation',
    longDescription: 'Lalal.ai extracts vocals, instruments, and stems from any audio file with high-quality AI-powered source separation.',
    category: 'Audio',
    trending: false,
    logoUrlId: 'logo-lalal-ai',
    website: 'https://www.lalal.ai',
    useCases: [],
  },
  {
    id: '104',
    slug: 'riverside-fm',
    name: 'Riverside.fm',
    description: 'AI-powered podcast and video recording studio',
    longDescription: 'Riverside.fm records studio-quality podcasts and videos remotely with AI transcription, editing, and enhancement features.',
    category: 'Audio',
    trending: false,
    logoUrlId: 'logo-riverside-fm',
    website: 'https://riverside.fm',
    useCases: [],
  },
  {
    id: '105',
    slug: 'voice-ai',
    name: 'Voice.ai',
    description: 'Free real-time AI voice changer',
    longDescription: 'Voice.ai is a free real-time voice changer with AI-powered voice cloning and custom voice creation for gaming and content.',
    category: 'Audio',
    trending: false,
    logoUrlId: 'logo-voice-ai',
    website: 'https://voice.ai',
    useCases: [],
  },
  {
    id: '106',
    slug: 'tabnine',
    name: 'Tabnine',
    description: 'AI code completion tool for all major IDEs',
    longDescription: 'Tabnine provides AI-powered code completions trained on your codebase. Works with all major programming languages and IDEs.',
    category: 'Coding',
    trending: false,
    logoUrlId: 'logo-tabnine',
    website: 'https://www.tabnine.com',
    useCases: [],
  },
  {
    id: '107',
    slug: 'codeium',
    name: 'Codeium',
    description: 'Free AI-powered code completion and chat',
    longDescription: 'Codeium offers free AI code completion, intelligent search, and AI chat for 70+ programming languages across all major IDEs.',
    category: 'Coding',
    trending: false,
    logoUrlId: 'logo-codeium',
    website: 'https://codeium.com',
    useCases: [],
  },
  {
    id: '108',
    slug: 'amazon-codewhisperer',
    name: 'Amazon CodeWhisperer',
    description: 'AI coding companion by AWS',
    longDescription: 'Amazon CodeWhisperer generates code suggestions and identifies security issues. Optimized for AWS APIs and best practices.',
    category: 'Coding',
    trending: false,
    logoUrlId: 'logo-amazon-codewhisperer',
    website: 'https://aws.amazon.com/codewhisperer',
    useCases: [],
  },
  {
    id: '109',
    slug: 'sourcegraph-cody',
    name: 'Sourcegraph Cody',
    description: 'AI coding assistant that understands your entire codebase',
    longDescription: 'Cody by Sourcegraph is an AI assistant that reads your entire codebase and helps you write, understand, and fix code faster.',
    category: 'Coding',
    trending: false,
    logoUrlId: 'logo-sourcegraph-cody',
    website: 'https://sourcegraph.com/cody',
    useCases: [],
  },
  {
    id: '110',
    slug: 'openai-codex',
    name: 'OpenAI Codex',
    description: "OpenAI's AI system that translates natural language to code",
    longDescription: 'OpenAI Codex powers GitHub Copilot and can translate natural language to code in Python, JavaScript, and dozen other languages.',
    category: 'Coding',
    trending: false,
    logoUrlId: 'logo-openai-codex',
    website: 'https://openai.com/blog/openai-codex',
    useCases: [],
  },
  {
    id: '111',
    slug: 'pieces',
    name: 'Pieces for Developers',
    description: 'AI-powered code snippet manager and workflow tool',
    longDescription: 'Pieces helps developers save, enrich, search, and reuse code snippets with AI-powered context and auto-classification.',
    category: 'Coding',
    trending: false,
    logoUrlId: 'logo-pieces',
    website: 'https://pieces.app',
    useCases: [],
  },
  {
    id: '112',
    slug: 'mintlify',
    name: 'Mintlify',
    description: 'AI documentation writer for code',
    longDescription: 'Mintlify automatically generates documentation for your code with AI. Create beautiful docs that developers actually use.',
    category: 'Coding',
    trending: false,
    logoUrlId: 'logo-mintlify',
    website: 'https://mintlify.com',
    useCases: [],
  },
  {
    id: '113',
    slug: 'phind',
    name: 'Phind',
    description: 'AI search engine for developers',
    longDescription: 'Phind is an AI-powered search engine specifically designed for developers. Get instant answers to technical questions with code examples.',
    category: 'Coding',
    trending: false,
    logoUrlId: 'logo-phind',
    website: 'https://www.phind.com',
    useCases: [],
  },
  {
    id: '114',
    slug: 'bito-ai',
    name: 'Bito AI',
    description: 'AI assistant for developers in IDE and CLI',
    longDescription: 'Bito AI helps developers write code faster, understand complex code, and generate unit tests directly in your IDE or command line.',
    category: 'Coding',
    trending: false,
    logoUrlId: 'logo-bito-ai',
    website: 'https://bito.ai',
    useCases: [],
  },
  {
    id: '115',
    slug: 'ghostwriter',
    name: 'Ghostwriter',
    description: 'AI pair programmer in Replit',
    longDescription: "Ghostwriter is Replit's AI assistant that helps you code faster with intelligent completions, code generation, and explanations.",
    category: 'Coding',
    trending: false,
    logoUrlId: 'logo-ghostwriter',
    website: 'https://replit.com/site/ghostwriter',
    useCases: [],
  },
  {
    id: '116',
    slug: 'codegeex',
    name: 'CodeGeeX',
    description: 'Multilingual AI code generation model',
    longDescription: 'CodeGeeX is a large-scale multilingual code generation model supporting 20+ programming languages with intelligent code completion.',
    category: 'Coding',
    trending: false,
    logoUrlId: 'logo-codegeex',
    website: 'https://codegeex.cn',
    useCases: [],
  },
  {
    id: '117',
    slug: 'refact-ai',
    name: 'Refact.ai',
    description: 'Open-source AI coding assistant',
    longDescription: 'Refact.ai is an open-source AI coding assistant with code completion, refactoring, and chat features that respects your privacy.',
    category: 'Coding',
    trending: false,
    logoUrlId: 'logo-refact-ai',
    website: 'https://refact.ai',
    useCases: [],
  },
  {
    id: '118',
    slug: 'warp-ai',
    name: 'Warp AI',
    description: 'AI-powered terminal with intelligent command suggestions',
    longDescription: 'Warp is a modern terminal with AI-powered command search, intelligent suggestions, and workflow automation features.',
    category: 'Coding',
    trending: false,
    logoUrlId: 'logo-warp-ai',
    website: 'https://www.warp.dev',
    useCases: [],
  },
  {
    id: '119',
    slug: 'otter-ai',
    name: 'Otter.ai',
    description: 'AI meeting assistant with transcription and notes',
    longDescription: 'Otter.ai records meetings, takes notes, and generates summaries automatically. Never miss important details from calls and meetings.',
    category: 'Productivity',
    trending: false,
    logoUrlId: 'logo-otter-ai',
    website: 'https://otter.ai',
    useCases: [],
  },
  {
    id: '120',
    slug: 'fireflies-ai',
    name: 'Fireflies.ai',
    description: 'AI meeting assistant that records, transcribes, and summarizes',
    longDescription: 'Fireflies.ai automatically joins meetings, records conversations, transcribes in real-time, and generates searchable summaries.',
    category: 'Productivity',
    trending: false,
    logoUrlId: 'logo-fireflies-ai',
    website: 'https://fireflies.ai',
    useCases: [],
  },
  {
    id: '121',
    slug: 'clockwise',
    name: 'Clockwise',
    description: 'AI-powered calendar optimization and scheduling',
    longDescription: 'Clockwise uses AI to optimize your calendar, protect focus time, and automatically schedule meetings at the best times.',
    category: 'Productivity',
    trending: false,
    logoUrlId: 'logo-clockwise',
    website: 'https://www.getclockwise.com',
    useCases: [],
  },
  {
    id: '122',
    slug: 'motion-app',
    name: 'Motion',
    description: 'AI calendar and project manager that builds your schedule',
    longDescription: 'Motion uses AI to automatically plan your day, schedule tasks, and manage projects. Get 25% more done with intelligent time blocking.',
    category: 'Productivity',
    trending: false,
    logoUrlId: 'logo-motion-app',
    website: 'https://www.usemotion.com',
    useCases: [],
  },
  {
    id: '123',
    slug: 'reclaim-ai',
    name: 'Reclaim AI',
    description: 'AI scheduling for teams and individuals',
    longDescription: 'Reclaim AI automatically schedules your habits, tasks, meetings, and breaks. Defend your time and increase productivity with smart scheduling.',
    category: 'Productivity',
    trending: false,
    logoUrlId: 'logo-reclaim-ai',
    website: 'https://reclaim.ai',
    useCases: [],
  },
  {
    id: '124',
    slug: 'superhuman',
    name: 'Superhuman',
    description: 'AI-powered email client for productivity',
    longDescription: 'Superhuman is the fastest email experience with AI triage, instant replies, and keyboard shortcuts to reach inbox zero.',
    category: 'Productivity',
    trending: false,
    logoUrlId: 'logo-superhuman',
    website: 'https://superhuman.com',
    useCases: [],
  },
  {
    id: '125',
    slug: 'mem-ai',
    name: 'Mem',
    description: 'AI-powered note-taking and knowledge management',
    longDescription: 'Mem is a self-organizing workspace powered by AI. Capture ideas, organize automatically, and surface relevant information when you need it.',
    category: 'Productivity',
    trending: false,
    logoUrlId: 'logo-mem-ai',
    website: 'https://mem.ai',
    useCases: [],
  },
  {
    id: '126',
    slug: 'tldv',
    name: 'tldv',
    description: 'AI meeting recorder for Google Meet and Zoom',
    longDescription: 'tldv records, transcribes, and summarizes your meetings automatically. Search through calls and share key moments instantly.',
    category: 'Productivity',
    trending: false,
    logoUrlId: 'logo-tldv',
    website: 'https://tldv.io',
    useCases: [],
  },
  {
    id: '127',
    slug: 'timely',
    name: 'Timely',
    description: 'AI-powered automatic time tracking',
    longDescription: 'Timely automatically tracks your time across all apps and websites. Get accurate timesheets without manual input.',
    category: 'Productivity',
    trending: false,
    logoUrlId: 'logo-timely',
    website: 'https://timelyapp.com',
    useCases: [],
  },
  {
    id: '128',
    slug: 'beforesunset-ai',
    name: 'BeforeSunset AI',
    description: 'AI daily planner that creates your schedule',
    longDescription: 'BeforeSunset AI creates personalized daily schedules based on your tasks, calendar, and preferences. Plan your perfect day with AI.',
    category: 'Productivity',
    trending: false,
    logoUrlId: 'logo-beforesunset-ai',
    website: 'https://beforesunset.ai',
    useCases: [],
  },
  {
    id: '129',
    slug: 'trevor-ai',
    name: 'Trevor AI',
    description: 'AI-powered task scheduling and time blocking',
    longDescription: 'Trevor AI helps you schedule tasks into your calendar with intelligent time blocking. Turn your to-do list into a concrete plan.',
    category: 'Productivity',
    trending: false,
    logoUrlId: 'logo-trevor-ai',
    website: 'https://trevorai.com',
    useCases: [],
  },
  {
    id: '130',
    slug: 'tactiq',
    name: 'Tactiq',
    description: 'AI meeting transcription and summaries',
    longDescription: 'Tactiq provides real-time transcription for Google Meet, Zoom, and Teams. Get AI-generated summaries and action items instantly.',
    category: 'Productivity',
    trending: false,
    logoUrlId: 'logo-tactiq',
    website: 'https://tactiq.io',
    useCases: [],
  },
  {
    id: '131',
    slug: 'magical',
    name: 'Magical',
    description: 'AI text expander and automation tool',
    longDescription: 'Magical uses AI to automate repetitive typing tasks. Create text shortcuts, autofill forms, and move data between apps instantly.',
    category: 'Productivity',
    trending: false,
    logoUrlId: 'logo-magical',
    website: 'https://www.getmagical.com',
    useCases: [],
  },
  {
    id: '132',
    slug: 'taskade',
    name: 'Taskade',
    description: 'AI-powered collaborative workspace for teams',
    longDescription: 'Taskade combines tasks, notes, mind maps, and video chat with AI. Collaborate and get work done faster with AI assistance.',
    category: 'Productivity',
    trending: false,
    logoUrlId: 'logo-taskade',
    website: 'https://www.taskade.com',
    useCases: [],
  },
  {
    id: '133',
    slug: 'surfer-seo',
    name: 'Surfer SEO',
    description: 'AI-powered SEO content optimization tool',
    longDescription: "Surfer SEO analyzes top-ranking pages and provides data-driven recommendations to improve your content's search rankings.",
    category: 'Marketing',
    trending: false,
    logoUrlId: 'logo-surfer-seo',
    website: 'https://surferseo.com',
    useCases: [],
  },
  {
    id: '134',
    slug: 'marketmuse',
    name: 'MarketMuse',
    description: 'AI content planning and optimization platform',
    longDescription: 'MarketMuse uses AI to research, plan, and optimize content strategy. Identify content gaps and create comprehensive topic coverage.',
    category: 'Marketing',
    trending: false,
    logoUrlId: 'logo-marketmuse',
    website: 'https://www.marketmuse.com',
    useCases: [],
  },
  {
    id: '135',
    slug: 'seventh-sense',
    name: 'Seventh Sense',
    description: 'AI email delivery optimization for HubSpot and Marketo',
    longDescription: 'Seventh Sense uses AI to optimize email send times for each contact, improving engagement and deliverability rates.',
    category: 'Marketing',
    trending: false,
    logoUrlId: 'logo-seventh-sense',
    website: 'https://www.theseventhsense.com',
    useCases: [],
  },
  {
    id: '136',
    slug: 'lavender-ai',
    name: 'Lavender',
    description: 'AI email coach for sales teams',
    longDescription: 'Lavender analyzes your emails and provides real-time coaching to improve response rates and book more meetings.',
    category: 'Marketing',
    trending: false,
    logoUrlId: 'logo-lavender-ai',
    website: 'https://www.lavender.ai',
    useCases: [],
  },
  {
    id: '137',
    slug: 'lately-ai',
    name: 'Lately AI',
    description: 'AI social media content generator',
    longDescription: 'Lately AI transforms long-form content into dozens of social media posts. Automate your social media content creation with AI.',
    category: 'Marketing',
    trending: false,
    logoUrlId: 'logo-lately-ai',
    website: 'https://www.lately.ai',
    useCases: [],
  },
  {
    id: '138',
    slug: 'adcreative-ai',
    name: 'AdCreative.ai',
    description: 'AI-powered ad creative generation',
    longDescription: 'AdCreative.ai generates conversion-focused ad creatives and social media posts using AI. Create high-performing ads in seconds.',
    category: 'Marketing',
    trending: false,
    logoUrlId: 'logo-adcreative-ai',
    website: 'https://www.adcreative.ai',
    useCases: [],
  },
  {
    id: '139',
    slug: 'persado',
    name: 'Persado',
    description: 'AI-powered marketing language optimization',
    longDescription: 'Persado uses AI to generate and optimize marketing language that drives higher engagement and conversions across all channels.',
    category: 'Marketing',
    trending: false,
    logoUrlId: 'logo-persado',
    website: 'https://www.persado.com',
    useCases: [],
  },
  {
    id: '140',
    slug: 'brandwatch',
    name: 'Brandwatch',
    description: 'AI-powered social media listening and analytics',
    longDescription: 'Brandwatch uses AI to analyze social media conversations, track brand mentions, and provide competitive intelligence insights.',
    category: 'Marketing',
    trending: false,
    logoUrlId: 'logo-brandwatch',
    website: 'https://www.brandwatch.com',
    useCases: [],
  },
  {
    id: '141',
    slug: 'phrasee',
    name: 'Phrasee',
    description: 'AI content generation for email and digital marketing',
    longDescription: 'Phrasee generates brand-compliant marketing copy that outperforms human writers. Optimize subject lines, push notifications, and ads with AI.',
    category: 'Marketing',
    trending: false,
    logoUrlId: 'logo-phrasee',
    website: 'https://www.phrasee.co',
    useCases: [],
  },
  {
    id: '142',
    slug: 'optimove',
    name: 'Optimove',
    description: 'AI-powered customer marketing platform',
    longDescription: 'Optimove uses AI to orchestrate personalized customer journeys across all channels, maximizing customer lifetime value.',
    category: 'Marketing',
    trending: false,
    logoUrlId: 'logo-optimove',
    website: 'https://www.optimove.com',
    useCases: [],
  },
  {
    id: '143',
    slug: 'albert-ai',
    name: 'Albert AI',
    description: 'Autonomous AI for digital marketing campaigns',
    longDescription: 'Albert AI autonomously manages and optimizes digital advertising campaigns across channels, continuously learning and improving performance.',
    category: 'Marketing',
    trending: false,
    logoUrlId: 'logo-albert-ai',
    website: 'https://albert.ai',
    useCases: [],
  },
  {
    id: '144',
    slug: 'cortex-social',
    name: 'Cortex',
    description: 'AI social media optimization and analytics',
    longDescription: 'Cortex analyzes your social media performance and provides AI-driven recommendations for content, posting times, and creative strategies.',
    category: 'Marketing',
    trending: false,
    logoUrlId: 'logo-cortex-social',
    website: 'https://www.meetcortex.com',
    useCases: [],
  },
  {
    id: '145',
    slug: 'drift',
    name: 'Drift',
    description: 'AI-powered conversational marketing platform',
    longDescription: 'Drift uses AI chatbots and conversational marketing to qualify leads, book meetings, and drive revenue through your website.',
    category: 'Marketing',
    trending: false,
    logoUrlId: 'logo-drift',
    website: 'https://www.drift.com',
    useCases: [],
  },
  {
    id: '146',
    slug: 'salesforce-einstein',
    name: 'Salesforce Einstein',
    description: 'AI layer for Salesforce CRM',
    longDescription: 'Einstein AI brings predictive analytics, intelligent automation, and AI-powered insights directly into your Salesforce workflows.',
    category: 'Business',
    trending: false,
    logoUrlId: 'logo-salesforce-einstein',
    website: 'https://www.salesforce.com/products/einstein',
    useCases: [],
  },
  {
    id: '147',
    slug: 'monday-ai',
    name: 'Monday.com',
    description: 'AI-powered work management platform',
    longDescription: 'Monday.com uses AI to automate workflows, generate content, and provide intelligent insights for better project management and collaboration.',
    category: 'Business',
    trending: false,
    logoUrlId: 'logo-monday-ai',
    website: 'https://monday.com',
    useCases: [],
  },
  {
    id: '148',
    slug: 'gong-ai',
    name: 'Gong',
    description: 'AI revenue intelligence platform',
    longDescription: 'Gong captures and analyzes all customer interactions to provide actionable insights that drive revenue growth and improve sales performance.',
    category: 'Business',
    trending: false,
    logoUrlId: 'logo-gong-ai',
    website: 'https://www.gong.io',
    useCases: [],
  },
  {
    id: '149',
    slug: 'chorus-ai',
    name: 'Chorus.ai',
    description: 'Conversation intelligence for sales teams',
    longDescription: 'Chorus.ai (by ZoomInfo) records and analyzes sales calls to provide coaching insights, deal intelligence, and market insights.',
    category: 'Business',
    trending: false,
    logoUrlId: 'logo-chorus-ai',
    website: 'https://www.chorus.ai',
    useCases: [],
  },
  {
    id: '150',
    slug: 'zendesk-ai',
    name: 'Zendesk AI',
    description: 'AI-powered customer service platform',
    longDescription: 'Zendesk AI helps customer service teams automate responses, route tickets intelligently, and provide personalized support at scale.',
    category: 'Business',
    trending: false,
    logoUrlId: 'logo-zendesk-ai',
    website: 'https://www.zendesk.com',
    useCases: [],
  },
  {
    id: '151',
    slug: 'hubspot-ai',
    name: 'HubSpot AI',
    description: 'AI-powered CRM and marketing automation',
    longDescription: 'HubSpot AI includes content generation, predictive lead scoring, and intelligent automation across marketing, sales, and service.',
    category: 'Business',
    trending: false,
    logoUrlId: 'logo-hubspot-ai',
    website: 'https://www.hubspot.com',
    useCases: [],
  },
  {
    id: '152',
    slug: 'intercom',
    name: 'Intercom',
    description: 'AI customer service and engagement platform',
    longDescription: 'Intercom uses AI to provide instant answers, route conversations, and help support teams deliver exceptional customer experiences.',
    category: 'Business',
    trending: false,
    logoUrlId: 'logo-intercom',
    website: 'https://www.intercom.com',
    useCases: [],
  },
  {
    id: '153',
    slug: 'pipedrive-ai',
    name: 'Pipedrive',
    description: 'AI-powered sales CRM',
    longDescription: 'Pipedrive uses AI to automate data entry, provide sales insights, and help sales teams close more deals with less manual work.',
    category: 'Business',
    trending: false,
    logoUrlId: 'logo-pipedrive-ai',
    website: 'https://www.pipedrive.com',
    useCases: [],
  },
  {
    id: '154',
    slug: 'freshworks-ai',
    name: 'Freshworks',
    description: 'AI-powered customer engagement suite',
    longDescription: 'Freshworks provides AI-powered solutions for customer service, sales, and marketing with intelligent automation and insights.',
    category: 'Business',
    trending: false,
    logoUrlId: 'logo-freshworks-ai',
    website: 'https://www.freshworks.com',
    useCases: [],
  },
  {
    id: '155',
    slug: 'zapier-ai',
    name: 'Zapier',
    description: 'AI-powered workflow automation platform',
    longDescription: 'Zapier connects your apps and automates workflows with AI. Build custom automations without code using natural language.',
    category: 'Business',
    trending: false,
    logoUrlId: 'logo-zapier-ai',
    website: 'https://zapier.com',
    useCases: [],
  },
  {
    id: '156',
    slug: 'outreach',
    name: 'Outreach',
    description: 'AI-powered sales execution platform',
    longDescription: 'Outreach uses AI to optimize sales sequences, provide real-time guidance, and help sales teams execute efficiently at scale.',
    category: 'Business',
    trending: false,
    logoUrlId: 'logo-outreach',
    website: 'https://www.outreach.io',
    useCases: [],
  },
  {
    id: '157',
    slug: 'trello-ai',
    name: 'Trello',
    description: 'AI-powered project management boards',
    longDescription: 'Trello uses AI to automate task management, generate summaries, and help teams organize projects more efficiently.',
    category: 'Business',
    trending: false,
    logoUrlId: 'logo-trello-ai',
    website: 'https://trello.com',
    useCases: [],
  },
  {
    id: '158',
    slug: 'clickup-ai',
    name: 'ClickUp',
    description: 'All-in-one productivity platform with AI',
    longDescription: 'ClickUp combines tasks, docs, goals, and chat with AI-powered writing, summarization, and project insights.',
    category: 'Business',
    trending: false,
    logoUrlId: 'logo-clickup-ai',
    website: 'https://clickup.com',
    useCases: [],
  },
  {
    id: '159',
    slug: 'airtable-ai',
    name: 'Airtable',
    description: 'AI-powered connected apps platform',
    longDescription: 'Airtable combines databases and AI to help teams build custom business applications without code.',
    category: 'Business',
    trending: false,
    logoUrlId: 'logo-airtable-ai',
    website: 'https://www.airtable.com',
    useCases: [],
  },
  {
    id: '160',
    slug: 'asana-ai',
    name: 'Asana',
    description: 'AI-powered work management platform',
    longDescription: 'Asana uses AI to automate workflows, provide intelligent summaries, and help teams coordinate work more effectively.',
    category: 'Business',
    trending: false,
    logoUrlId: 'logo-asana-ai',
    website: 'https://asana.com',
    useCases: [],
  },
  {
    id: '161',
    slug: 'semrush',
    name: 'Semrush',
    description: 'All-in-one SEO and competitive research platform',
    longDescription: 'Semrush provides comprehensive SEO tools including keyword research, competitor analysis, site audits, and content optimization powered by AI.',
    category: 'SEO',
    trending: false,
    logoUrlId: 'logo-semrush',
    website: 'https://www.semrush.com',
    useCases: [],
  },
  {
    id: '162',
    slug: 'ahrefs',
    name: 'Ahrefs',
    description: 'SEO toolset for backlinks and competitive analysis',
    longDescription: 'Ahrefs offers powerful tools for backlink analysis, keyword research, content exploration, and rank tracking with AI-powered insights.',
    category: 'SEO',
    trending: false,
    logoUrlId: 'logo-ahrefs',
    website: 'https://ahrefs.com',
    useCases: [],
  },
  {
    id: '163',
    slug: 'moz-pro',
    name: 'Moz Pro',
    description: 'Comprehensive SEO software suite',
    longDescription: 'Moz Pro provides keyword research, link building, site audits, and page optimization tools to help you improve search rankings.',
    category: 'SEO',
    trending: false,
    logoUrlId: 'logo-moz-pro',
    website: 'https://moz.com',
    useCases: [],
  },
  {
    id: '164',
    slug: 'clearscope',
    name: 'Clearscope',
    description: 'AI-powered SEO content optimization',
    longDescription: 'Clearscope analyzes top-ranking content and provides AI-driven recommendations to optimize your content for better search visibility.',
    category: 'SEO',
    trending: false,
    logoUrlId: 'logo-clearscope',
    website: 'https://www.clearscope.io',
    useCases: [],
  },
  {
    id: '165',
    slug: 'se-ranking',
    name: 'SE Ranking',
    description: 'All-in-one SEO platform with AI features',
    longDescription: 'SE Ranking offers keyword rank tracking, website audits, competitor analysis, and AI-powered content tools for SEO professionals.',
    category: 'SEO',
    trending: false,
    logoUrlId: 'logo-se-ranking',
    website: 'https://seranking.com',
    useCases: [],
  },
  {
    id: '166',
    slug: 'ubersuggest',
    name: 'Ubersuggest',
    description: 'Affordable SEO tool by Neil Patel',
    longDescription: 'Ubersuggest provides keyword ideas, content suggestions, backlink data, and site audits at an affordable price point.',
    category: 'SEO',
    trending: false,
    logoUrlId: 'logo-ubersuggest',
    website: 'https://neilpatel.com/ubersuggest',
    useCases: [],
  },
  {
    id: '167',
    slug: 'seo-ai',
    name: 'SEO.ai',
    description: 'AI-powered SEO content creation and optimization',
    longDescription: 'SEO.ai combines AI writing with SEO optimization to help you create content that ranks higher in search engines.',
    category: 'SEO',
    trending: false,
    logoUrlId: 'logo-seo-ai',
    website: 'https://seo.ai',
    useCases: [],
  },
  {
    id: '168',
    slug: 'brightedge',
    name: 'BrightEdge',
    description: 'Enterprise SEO and content performance platform',
    longDescription: 'BrightEdge is an enterprise SEO platform with AI-powered insights for content optimization, competitive intelligence, and performance tracking.',
    category: 'SEO',
    trending: false,
    logoUrlId: 'logo-brightedge',
    website: 'https://www.brightedge.com',
    useCases: [],
  },
  {
    id: '169',
    slug: 'screaming-frog',
    name: 'Screaming Frog',
    description: 'SEO spider tool for technical audits',
    longDescription: 'Screaming Frog crawls websites to identify SEO issues, broken links, and technical problems that affect search performance.',
    category: 'SEO',
    trending: false,
    logoUrlId: 'logo-screaming-frog',
    website: 'https://www.screamingfrog.co.uk',
    useCases: [],
  },
  {
    id: '170',
    slug: 'spyfu',
    name: 'SpyFu',
    description: 'Competitor keyword and SEO research tool',
    longDescription: "SpyFu reveals your competitors' most profitable keywords, ad campaigns, and SEO strategies for search and PPC.",
    category: 'SEO',
    trending: false,
    logoUrlId: 'logo-spyfu',
    website: 'https://www.spyfu.com',
    useCases: [],
  },
  {
    id: '171',
    slug: 'mangools',
    name: 'Mangools',
    description: 'SEO tools suite for keyword and link research',
    longDescription: 'Mangools offers user-friendly SEO tools including KWFinder for keywords, SERPChecker, and LinkMiner for backlink analysis.',
    category: 'SEO',
    trending: false,
    logoUrlId: 'logo-mangools',
    website: 'https://mangools.com',
    useCases: [],
  },
  {
    id: '172',
    slug: 'serpstat',
    name: 'Serpstat',
    description: 'All-in-one SEO platform for growth hackers',
    longDescription: 'Serpstat provides keyword research, rank tracking, site audits, and competitor analysis in one affordable platform.',
    category: 'SEO',
    trending: false,
    logoUrlId: 'logo-serpstat',
    website: 'https://serpstat.com',
    useCases: [],
  },
  {
    id: '173',
    slug: 'rank-math',
    name: 'Rank Math',
    description: 'WordPress SEO plugin with AI features',
    longDescription: 'Rank Math is a powerful WordPress SEO plugin with AI-powered content analysis, schema markup, and optimization recommendations.',
    category: 'SEO',
    trending: false,
    logoUrlId: 'logo-rank-math',
    website: 'https://rankmath.com',
    useCases: [],
  },
  {
    id: '174',
    slug: 'yoast-seo',
    name: 'Yoast SEO',
    description: 'Popular WordPress SEO plugin',
    longDescription: 'Yoast SEO helps optimize WordPress sites for search engines with real-time content analysis, XML sitemaps, and technical SEO features.',
    category: 'SEO',
    trending: false,
    logoUrlId: 'logo-yoast-seo',
    website: 'https://yoast.com',
    useCases: [],
  },
  {
    id: '175',
    slug: 'contentking',
    name: 'ContentKing',
    description: 'Real-time SEO auditing and monitoring',
    longDescription: 'ContentKing provides real-time SEO auditing, change tracking, and alerts to help you maintain and improve search rankings.',
    category: 'SEO',
    trending: false,
    logoUrlId: 'logo-contentking',
    website: 'https://www.contentkingapp.com',
    useCases: [],
  },
  {
    id: '176',
    slug: 'tidio',
    name: 'Tidio',
    description: 'Live chat and AI chatbot platform',
    longDescription: 'Tidio combines live chat with AI chatbots to automate customer service, capture leads, and increase sales on your website.',
    category: 'Chatbot',
    trending: false,
    logoUrlId: 'logo-tidio',
    website: 'https://www.tidio.com',
    useCases: [],
  },
  {
    id: '177',
    slug: 'manychat',
    name: 'ManyChat',
    description: 'Chat marketing platform for Instagram and Facebook',
    longDescription: 'ManyChat automates conversations on Instagram, Facebook Messenger, and SMS with AI-powered chatbots for marketing and sales.',
    category: 'Chatbot',
    trending: false,
    logoUrlId: 'logo-manychat',
    website: 'https://manychat.com',
    useCases: [],
  },
  {
    id: '178',
    slug: 'chatfuel',
    name: 'Chatfuel',
    description: 'No-code chatbot builder for messaging apps',
    longDescription: 'Chatfuel lets you build AI chatbots for Facebook, Instagram, and WhatsApp without coding. Automate customer support and marketing.',
    category: 'Chatbot',
    trending: false,
    logoUrlId: 'logo-chatfuel',
    website: 'https://chatfuel.com',
    useCases: [],
  },
  {
    id: '179',
    slug: 'landbot',
    name: 'Landbot',
    description: 'No-code chatbot builder for websites and WhatsApp',
    longDescription: 'Landbot creates conversational experiences for websites, WhatsApp, and Facebook with an easy drag-and-drop interface.',
    category: 'Chatbot',
    trending: false,
    logoUrlId: 'logo-landbot',
    website: 'https://landbot.io',
    useCases: [],
  },
  {
    id: '180',
    slug: 'ada-cx',
    name: 'Ada',
    description: 'Enterprise AI chatbot for customer service',
    longDescription: 'Ada provides enterprise-grade AI chatbots that automate customer support across channels, reducing costs and improving satisfaction.',
    category: 'Chatbot',
    trending: false,
    logoUrlId: 'logo-ada-cx',
    website: 'https://www.ada.cx',
    useCases: [],
  },
  {
    id: '181',
    slug: 'dialogflow',
    name: 'Dialogflow',
    description: "Google's conversational AI platform",
    longDescription: 'Dialogflow (by Google Cloud) builds natural language understanding into chatbots and voice assistants with powerful AI models.',
    category: 'Chatbot',
    trending: false,
    logoUrlId: 'logo-dialogflow',
    website: 'https://cloud.google.com/dialogflow',
    useCases: [],
  },
  {
    id: '182',
    slug: 'rasa',
    name: 'Rasa',
    description: 'Open-source conversational AI platform',
    longDescription: 'Rasa is an open-source framework for building contextual AI assistants and chatbots with full control over your data and models.',
    category: 'Chatbot',
    trending: false,
    logoUrlId: 'logo-rasa',
    website: 'https://rasa.com',
    useCases: [],
  },
  {
    id: '183',
    slug: 'botpress',
    name: 'Botpress',
    description: 'Open-source chatbot platform',
    longDescription: 'Botpress is an open-source conversational AI platform for building, deploying, and managing enterprise chatbots.',
    category: 'Chatbot',
    trending: false,
    logoUrlId: 'logo-botpress',
    website: 'https://botpress.com',
    useCases: [],
  },
  {
    id: '184',
    slug: 'voiceflow',
    name: 'Voiceflow',
    description: 'Collaborative platform for designing chat and voice assistants',
    longDescription: 'Voiceflow enables teams to design, prototype, and build AI agents for chat and voice with a visual collaborative interface.',
    category: 'Chatbot',
    trending: false,
    logoUrlId: 'logo-voiceflow',
    website: 'https://www.voiceflow.com',
    useCases: [],
  },
  {
    id: '185',
    slug: 'kore-ai',
    name: 'Kore.ai',
    description: 'Enterprise conversational AI platform',
    longDescription: 'Kore.ai builds intelligent virtual assistants for enterprises with advanced NLU, multi-channel deployment, and analytics.',
    category: 'Chatbot',
    trending: false,
    logoUrlId: 'logo-kore-ai',
    website: 'https://kore.ai',
    useCases: [],
  },
  {
    id: '186',
    slug: 'tars',
    name: 'Tars',
    description: 'Conversational landing pages and chatbots',
    longDescription: 'Tars creates conversational landing pages and chatbots that replace traditional presidential to boost conversions and engagement.',
    category: 'Chatbot',
    trending: false,
    logoUrlId: 'logo-tars',
    website: 'https://hellotars.com',
    useCases: [],
  },
  {
    id: '187',
    slug: 'yellow-ai',
    name: 'Yellow.ai',
    description: 'Enterprise-grade conversational AI platform',
    longDescription: 'Yellow.ai provides enterprise conversational AI solutions for customer service, employee support, and process automation.',
    category: 'Chatbot',
    trending: false,
    logoUrlId: 'logo-yellow-ai',
    website: 'https://yellow.ai',
    useCases: [],
  },
  {
    id: '188',
    slug: 'chatbot-com',
    name: 'Chatbot.com',
    description: 'All-in-one chatbot platform',
    longDescription: 'Chatbot.com provides an all-in-one platform to build, test, and deploy chatbots across multiple channels without coding.',
    category: 'Chatbot',
    trending: false,
    logoUrlId: 'logo-chatbot-com',
    website: 'https://www.chatbot.com',
    useCases: [],
  },
  {
    id: '189',
    slug: 'crisp',
    name: 'Crisp',
    description: 'Business messaging platform with AI chatbot',
    longDescription: 'Crisp combines live chat, email, and social messaging with AI chatbots for seamless customer communication and support.',
    category: 'Chatbot',
    trending: false,
    logoUrlId: 'logo-crisp',
    website: 'https://crisp.chat',
    useCases: [],
  },
  {
    id: '190',
    slug: 'you-com',
    name: 'You.com',
    description: 'AI search engine with customizable results',
    longDescription: 'You.com is an AI-powered search engine that gives you personalized results with apps, summaries, and the ability to chat with AI.',
    category: 'Search',
    trending: false,
    logoUrlId: 'logo-you-com',
    website: 'https://you.com',
    useCases: [],
  },
  {
    id: '191',
    slug: 'bing-ai',
    name: 'Bing AI',
    description: "Microsoft's AI-powered search with GPT-4",
    longDescription: 'Bing AI combines traditional search with GPT-4 powered chat to provide comprehensive answers, create content, and help with complex queries.',
    category: 'Search',
    trending: false,
    logoUrlId: 'logo-bing-ai',
    website: 'https://www.bing.com',
    useCases: [],
  },
  {
    id: '192',
    slug: 'brave-search',
    name: 'Brave Search',
    description: 'Privacy-focused search engine with AI features',
    longDescription: 'Brave Search offers private, independent search results with AI-powered summaries without tracking or profiling users.',
    category: 'Search',
    trending: false,
    logoUrlId: 'logo-brave-search',
    website: 'https://search.brave.com',
    useCases: [],
  },
  {
    id: '193',
    slug: 'metaphor',
    name: 'Metaphor',
    description: 'AI-powered search for finding similar content',
    longDescription: 'Metaphor uses AI to understand intent and find similar content across the web. Perfect for research and discovery.',
    category: 'Search',
    trending: false,
    logoUrlId: 'logo-metaphor',
    website: 'https://metaphor.systems',
    useCases: [],
  },
  {
    id: '194',
    slug: 'consensus',
    name: 'Consensus',
    description: 'AI search engine for scientific research papers',
    longDescription: 'Consensus searches through scientific research papers and uses AI to extract key findings and synthesize results.',
    category: 'Search',
    trending: false,
    logoUrlId: 'logo-consensus',
    website: 'https://consensus.app',
    useCases: [],
  },
  {
    id: '195',
    slug: 'elicit',
    name: 'Elicit',
    description: 'AI research assistant for literature reviews',
    longDescription: 'Elicit automates research workflows like literature reviews. Find relevant papers, extract key information, and synthesize findings with AI.',
    category: 'Search',
    trending: false,
    logoUrlId: 'logo-elicit',
    website: 'https://elicit.org',
    useCases: [],
  },
  {
    id: '196',
    slug: 'komo-ai',
    name: 'Komo AI',
    description: 'Private AI-powered search engine',
    longDescription: 'Komo AI provides fast, private search results with AI-generated answers and no ads or tracking.',
    category: 'Search',
    trending: false,
    logoUrlId: 'logo-komo-ai',
    website: 'https://komo.ai',
    useCases: [],
  },
  {
    id: '197',
    slug: 'andi',
    name: 'Andi',
    description: 'Conversational AI search engine',
    longDescription: 'Andi is a conversational search engine that answers questions with AI instead of just links. Get direct answers in a chat interface.',
    category: 'Search',
    trending: false,
    logoUrlId: 'logo-andi',
    website: 'https://andisearch.com',
    useCases: [],
  },
  {
    id: '198',
    slug: 'neeva',
    name: 'Neeva',
    description: 'Ad-free search engine with AI',
    longDescription: 'Neeva provides ad-free search with AI-powered features and personalization without tracking or selling your data.',
    category: 'Search',
    trending: false,
    logoUrlId: 'logo-neeva',
    website: 'https://neeva.com',
    useCases: [],
  },
  {
    id: '199',
    slug: 'waldo',
    name: 'Waldo',
    description: 'AI search for documents and files',
    longDescription: 'Waldo searches across all your documents, files, and apps to find what you need instantly with AI-powered understanding.',
    category: 'Search',
    trending: false,
    logoUrlId: 'logo-waldo',
    website: 'https://waldo.fyi',
    useCases: [],
  },
];


const articles: Article[] = [
  {
    id: '7',
    slug: 'nerovet-ai-dental-analysis',
    title: NerovetArticle.title,
    excerpt: NerovetArticle.description,
    date: NerovetArticle.date,
    author: NerovetArticle.author,
    imageUrlId: 'article-image-nerovet',
    content: NerovetArticle.content,
    tags: ['Dental AI', 'Analysis', 'Health Tech'],
    readTime: 18,
  },
  {
    id: '6',
    slug: 'openai-operator-action-era',
    title: OperatorArticle.title,
    excerpt: OperatorArticle.description,
    date: OperatorArticle.date,
    author: OperatorArticle.author,
    imageUrlId: 'article-image-operator',
    content: OperatorArticle.content,
    tags: ['Breaking News', 'Action Era'],
    readTime: 5,
  },
  {
    id: '5',
    slug: 'openclaw-moltbot-viral-phenomenon',
    title: OpenClawArticle.title,
    excerpt: OpenClawArticle.description,
    date: '2026-01-31',
    author: 'AI Tools Korner Staff',
    imageUrlId: 'article-image-openclaw',
    content: OpenClawArticle.content,
    tags: ['Deep Dive', 'Security'],
    readTime: 7,
  },
  {
    id: '4',
    slug: 'nvidia-halts-investment-in-openai-deep-dive',
    title: NvideaArticle.title,
    excerpt: NvideaArticle.description,
    date: '2026-02-01',
    author: NvideaArticle.author,
    imageUrlId: 'article-image-nvidia',
    content: NvideaArticle.content,
    tags: ['Industry News', 'Analysis'],
    readTime: 6,
  },
  {
    id: '1',
    slug: 'ai-girlfriend-companionship-digital-age',
    title: 'The Rise of AI Girlfriends: Companionship in the Digital Age',
    excerpt: 'Exploring the fast-growing world of AI companions. What\'s the appeal, what\'s the tech, and what are the ethical questions we need to ask?',
    date: '2024-07-20',
    author: 'AI Tools Korner Staff',
    imageUrlId: 'article-image-1',
    content: article1Content,
    tags: ['Ethics', 'Social'],
    readTime: 2,
  },
  {
    id: '2',
    slug: 'ai-video-revolution-sora-pika-runway',
    title: 'AI News, Pika, Runway: The AI Video Revolution is Here',
    excerpt: 'From OpenAI\'s Sora to competitors like Pika and Runway, text-to-video AI is changing filmmaking and content creation forever. How does it work and what\'s next?',
    date: '2024-07-18',
    author: 'Alex Ray',
    imageUrlId: 'article-image-2',
    content: article2Content,
    tags: ['Generative AI', 'Video'],
    readTime: 2,
  },
  {
    id: '3',
    slug: 'ai-agents-autonomous-workforce',
    title: 'Forget AI Tools, Meet Your New AI Agent',
    excerpt: 'The next evolution of AI is here: autonomous agents that can complete complex tasks on their own. Are they the future of productivity or a threat to jobs?',
    date: '2024-07-16',
    author: 'Jane Doe',
    imageUrlId: 'article-image-3',
    content: article3Content,
    tags: ['Productivity', 'Future of Work'],
    readTime: 2,
  }
];

export function getTools(): Tool[] {
  const orderedTools = [
    'suno', 'udio', 'mubert', 'stable-audio', 'soundraw', 'aiva', 'beatoven-ai', 'soundverse', 'musicfy', 'boomy', 'loudly', 'soundful', 'splash-pro', 'wavtool', 'amadeus-code', 'harmonai', 'riffusion', 'ecrett-music', 'songburst', 'amper-music'
  ];
  
  const sortedMusicTools = tools
    .filter(t => orderedTools.includes(t.slug))
    .sort((a, b) => orderedTools.indexOf(a.slug) - orderedTools.indexOf(b.slug));

  const otherTools = tools.filter(t => !orderedTools.includes(t.slug));

  return [...sortedMusicTools, ...otherTools];
}

export function getArticles(): Article[] {
  return articles;
}

export function getToolBySlug(slug: string): Tool | undefined {
  return tools.find((tool) => tool.slug === slug);
}

export function getArticleBySlug(slug: string): Article | undefined {
  return articles.find((article) => article.slug === slug);
}

export function getTrendingTools(): Tool[] {
  return tools.filter((tool) => tool.trending);
}

export function getLatestArticles(count: number): Article[] {
  return [...articles]
    .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime())
    .slice(0, count);
}

export function getAllCategories(): Category[] {
  return CATEGORIES;
}

export function getCategoryBySlug(slug: string): Category | undefined {
  return CATEGORIES.find((cat) => cat.slug === slug);
}

export function getToolsByCategory(category: ToolCategory): Tool[] {
  return tools.filter((tool) => tool.category === category);
}

export function getAllUseCases(): UseCase[] {
  return USE_CASES;
}

export function getUseCaseBySlug(slug: string): UseCase | undefined {
  return USE_CASES.find((uc) => uc.slug === slug);
}

export function getToolsByUseCase(useCaseSlug: string): Tool[] {
  return tools.filter((tool) => tool.useCases?.includes(useCaseSlug));
}

export function getAlternativeTools(currentTool: Tool): Tool[] {
  return tools
    .filter(
      (tool) =>
        tool.category === currentTool.category && tool.id !== currentTool.id
    )
    .slice(0, 4);
}
