import type { Tool, Article, ToolCategory, Category, UseCase } from './types';
import { content as article1Content } from './articles/ai-girlfriend-companionship-digital-age';
import { content as article2Content } from './articles/ai-video-revolution-sora-pika-runway';
import { content as article3Content } from './articles/ai-agents-autonomous-workforce';

const CATEGORIES: Category[] = [
  { slug: 'writing', name: 'Writing', description: 'Tools to assist with writing, editing, and content creation.' },
  { slug: 'image', name: 'Image', description: 'Generate, edit, and enhance images with AI.' },
  { slug: 'video', name: 'Video', description: 'Create and edit videos with AI-powered features.' },
  { slug: 'audio', name: 'Audio', description: 'Tools for audio generation, editing, and transcription.' },
  { slug: 'coding', name: 'Coding', description: 'AI assistants for writing and debugging code.' },
  { slug: 'productivity', name: 'Productivity', description: 'Boost your efficiency and organization.' },
  { slug: 'marketing', name: 'Marketing', description: 'AI tools for marketing, SEO, and social media.' },
  { slug: 'business', name: 'Business', description: 'Solutions for business intelligence and operations.' },
  { slug: 'seo', name: 'SEO', description: 'Optimize your content for search engines.' },
  { slug: 'chatbot', name: 'Chatbot', description: 'Engage with users through conversational AI assistants.' },
  { slug: 'design', name: 'Design', description: 'Create graphics and designs with AI-powered tools.' },
  { slug: 'research', name: 'Research', description: 'AI-powered tools for research and information gathering.' },
  { slug: 'search', name: 'Search', description: 'Next-generation search engines powered by AI.' },
  { slug: 'development', name: 'Development', description: 'Tools and platforms for AI application development.' },
  { slug: 'presentations', name: 'Presentations', description: 'Create compelling presentations with AI assistance.' },
  { slug: 'voice', name: 'Voice', description: 'Tools for voice synthesis and audio manipulation.' },
  { slug: 'music', name: 'Music', description: 'Generate original music and soundscapes with AI.' },
  { slug: 'hosting', name: 'Hosting', description: 'Platforms for deploying and hosting web applications.' },
];

const USE_CASES: UseCase[] = [
  { slug: 'writers', name: 'Writers', description: 'Enhance your writing process and creativity.' },
  { slug: 'students', name: 'Students', description: 'Tools for research, studying, and assignments.' },
  { slug: 'creators', name: 'Creators', description: 'For content creators, artists, and designers.' },
  { slug: 'startups', name: 'Startups', description: 'Scale your business with AI-powered solutions.' },
  { slug: 'developers', name: 'Developers', description: 'Code faster and smarter with AI assistants.' },
];

const tools: Tool[] = [
  {
    id: '1',
    slug: 'chatgpt',
    name: 'ChatGPT',
    description: "OpenAI's conversational AI for writing, coding, analysis, and creative tasks.",
    longDescription: "ChatGPT is a state-of-the-art conversational AI from OpenAI. It can generate human-like text for a variety of applications, from writing emails and essays to coding and answering complex questions. Its versatility makes it an indispensable tool for writers, developers, and students.",
    category: 'Writing',
    trending: true,
    logoUrlId: 'logo-chatgpt',
    website: 'https://chat.openai.com',
    useCases: ['writers', 'developers', 'students', 'creators'],
  },
  {
    id: '2',
    slug: 'claude',
    name: 'Claude',
    description: "Anthropic's AI assistant for analysis, writing, coding, and long-form content.",
    longDescription: "Claude is a next-generation AI assistant from Anthropic, designed to be helpful, harmless, and honest. It specializes in handling long-form content, making it ideal for summarizing large documents, answering questions about complex topics, and collaborative writing.",
    category: 'Writing',
    trending: true,
    logoUrlId: 'logo-claude',
    website: 'https://claude.ai',
    useCases: ['writers', 'research', 'students'],
  },
  {
    id: '3',
    slug: 'jasper-ai',
    name: 'Jasper AI',
    description: 'AI copywriting tool for marketing content, blogs, and social media.',
    longDescription: "Jasper AI is a leading AI copywriting tool that helps marketers and businesses create high-converting content at scale. From blog posts and social media updates to ad copy and product descriptions, Jasper accelerates the content creation process with its powerful AI engine.",
    category: 'Marketing',
    logoUrlId: 'logo-jasper',
    website: 'https://www.jasper.ai',
    useCases: ['marketing', 'writers', 'startups'],
  },
  {
    id: '4',
    slug: 'copy-ai',
    name: 'Copy.ai',
    description: 'AI-powered marketing copy and content generation tool.',
    longDescription: "Copy.ai is a versatile AI-powered platform for generating marketing copy and various types of content. It provides a suite of tools to help users overcome writer's block, brainstorm ideas, and produce polished copy for websites, emails, and social media.",
    category: 'Marketing',
    logoUrlId: 'logo-copy-ai',
    website: 'https://www.copy.ai',
    useCases: ['marketing', 'writers', 'startups'],
  },
  {
    id: '5',
    slug: 'perplexity-ai',
    name: 'Perplexity AI',
    description: 'AI-powered search engine with cited sources and conversational answers.',
    longDescription: "Perplexity AI is an innovative AI search engine that provides direct, cited answers to questions. It functions as a conversational 'answer engine' by synthesizing information from multiple sources on the web, complete with citations, to deliver trustworthy and accurate results.",
    category: 'Search',
    trending: true,
    logoUrlId: 'logo-perplexity',
    website: 'https://www.perplexity.ai',
    useCases: ['students', 'research', 'writers'],
  },
  {
    id: '6',
    slug: 'midjourney',
    name: 'Midjourney',
    description: 'AI art generator creating stunning images from text prompts.',
    longDescription: "Midjourney is a renowned AI art generator that produces high-quality, artistic images from simple text prompts. Accessed through Discord, it allows users to create stunning visuals in a wide range of styles, making it a favorite among artists, designers, and hobbyists.",
    category: 'Image',
    trending: true,
    logoUrlId: 'logo-midjourney',
    website: 'https://www.midjourney.com',
    useCases: ['creators', 'designers', 'artists'],
  },
  {
    id: '7',
    slug: 'dall-e-3',
    name: 'DALL-E 3',
    description: "OpenAI's advanced text-to-image generation model.",
    longDescription: "DALL-E 3 is OpenAI's most advanced text-to-image model, capable of generating highly detailed and contextually accurate images from natural language descriptions. It is integrated into ChatGPT Plus, allowing for an interactive and iterative image creation process.",
    category: 'Image',
    logoUrlId: 'logo-dall-e-3',
    website: 'https://openai.com/dall-e-3',
    useCases: ['creators', 'designers', 'artists'],
  },
  {
    id: '8',
    slug: 'canva-ai',
    name: 'Canva AI',
    description: 'Design platform with AI-powered features like Magic Write and text-to-image.',
    longDescription: "Canva AI integrates a suite of artificial intelligence features into the popular Canva design platform. This includes 'Magic Write' for text generation and a powerful text-to-image generator, empowering users to create professional designs more efficiently.",
    category: 'Design',
    logoUrlId: 'logo-canva',
    website: 'https://www.canva.com',
    useCases: ['creators', 'marketing', 'startups'],
  },
  {
    id: '9',
    slug: 'stable-diffusion',
    name: 'Stable Diffusion',
    description: 'Open-source AI image generation model.',
    longDescription: "Stable Diffusion is a powerful, open-source text-to-image model developed by Stability AI. Its open nature allows developers and users to run it on their own hardware, customize it, and integrate it into various applications, fostering a vibrant community of innovation.",
    category: 'Image',
    logoUrlId: 'logo-stable-diffusion',
    website: 'https://stability.ai',
    useCases: ['developers', 'creators', 'artists'],
  },
  {
    id: '10',
    slug: 'github-copilot',
    name: 'GitHub Copilot',
    description: 'AI pair programmer that suggests code completions.',
    longDescription: "GitHub Copilot is an AI pair programmer that provides intelligent code suggestions right inside your editor. It's trained on billions of lines of code, helping developers write code faster, learn new languages, and reduce boilerplate.",
    category: 'Coding',
    logoUrlId: 'logo-github-copilot',
    website: 'https://github.com/features/copilot',
    useCases: ['developers', 'startups'],
  },
  {
    id: '11',
    slug: 'cursor',
    name: 'Cursor',
    description: 'AI-first code editor built on VS Code with intelligent code generation.',
    longDescription: "Cursor is an AI-first code editor designed for modern software development. Built on VS Code, it offers intelligent code generation, editing, and debugging capabilities, allowing you to build software faster and more efficiently with the help of AI.",
    category: 'Coding',
    trending: true,
    logoUrlId: 'logo-cursor',
    website: 'https://www.cursor.so',
    useCases: ['developers'],
  },
  {
    id: '12',
    slug: 'bolt-new',
    name: 'Bolt.new',
    description: 'AI-powered full-stack web development in the browser by StackBlitz.',
    longDescription: "Bolt.new, from StackBlitz, is an AI-powered tool that enables full-stack web development directly in the browser. It helps you scaffold, build, and deploy web applications with AI assistance, streamlining the development workflow.",
    category: 'Development',
    trending: true,
    logoUrlId: 'logo-bolt-new',
    website: 'https://bolt.new',
    useCases: ['developers', 'startups'],
  },
  {
    id: '13',
    slug: 'v0-by-vercel',
    name: 'v0 by Vercel',
    description: 'AI-powered UI generation tool that creates React components.',
    longDescription: "v0.dev is a generative UI tool by Vercel that creates React components based on text prompts and images. It allows developers to rapidly prototype and build user interfaces using AI, generating production-ready code that can be easily copied and customized.",
    category: 'Development',
    trending: true,
    logoUrlId: 'logo-v0',
    website: 'https://v0.dev',
    useCases: ['developers', 'designers'],
  },
  {
    id: '14',
    slug: 'replit-ai',
    name: 'Replit AI',
    description: 'AI-powered collaborative coding environment.',
    longDescription: "Replit AI brings artificial intelligence into the collaborative, browser-based Replit IDE. It assists with code completion, explanation, and generation, making it a powerful tool for learning, prototyping, and building applications.",
    category: 'Coding',
    logoUrlId: 'logo-replit',
    website: 'https://replit.com',
    useCases: ['developers', 'students'],
  },
  {
    id: '15',
    slug: 'notion-ai',
    name: 'Notion AI',
    description: 'AI-powered workspace for notes, docs, and project management.',
    longDescription: "Notion AI integrates the power of artificial intelligence directly into your Notion workspace. It can summarize notes, draft content, brainstorm ideas, and organize information, turning your notes, docs, and projects into a more dynamic and intelligent system.",
    category: 'Productivity',
    logoUrlId: 'logo-notion',
    website: 'https://www.notion.so/product/ai',
    useCases: ['students', 'writers', 'startups'],
  },
  {
    id: '16',
    slug: 'gamma',
    name: 'Gamma',
    description: 'AI-powered presentation and document creation.',
    longDescription: "Gamma is an AI-powered tool for creating engaging presentations, documents, and webpages. Instead of designing slide by slide, you can generate a polished and professional-looking presentation from a simple text prompt, saving hours of work.",
    category: 'Presentations',
    logoUrlId: 'logo-gamma',
    website: 'https://gamma.app',
    useCases: ['students', 'startups', 'marketing'],
  },
  {
    id: '17',
    slug: 'descript',
    name: 'Descript',
    description: 'AI-powered video and podcast editing with transcription.',
    longDescription: "Descript revolutionizes audio and video editing by making it as simple as editing a text document. Its AI-powered features include automatic transcription, filler word removal, and Overdub, which lets you create a text-to-speech model of your own voice.",
    category: 'Video',
    logoUrlId: 'logo-descript',
    website: 'https://www.descript.com',
    useCases: ['creators', 'podcasters', 'video-editors'],
  },
  {
    id: '18',
    slug: 'google-ai-studio',
    name: 'Google AI Studio',
    description: "Google's platform for experimenting with Gemini models.",
    longDescription: "Google AI Studio is a web-based platform that allows developers to experiment with and prototype using Google's latest Gemini models. It provides a user-friendly interface to test prompts and explore the capabilities of Google's powerful AI.",
    category: 'Development',
    logoUrlId: 'logo-google-ai',
    website: 'https://aistudio.google.com',
    useCases: ['developers', 'research'],
  },
  {
    id: '19',
    slug: 'hugging-face',
    name: 'Hugging Face',
    description: 'Platform for building, training, and deploying ML models.',
    longDescription: "Hugging Face is the leading open-source platform for machine learning. It provides a vast repository of pre-trained models, datasets, and tools, enabling developers and researchers to build, train, and deploy state-of-the-art AI applications.",
    category: 'Development',
    logoUrlId: 'logo-hugging-face',
    website: 'https://huggingface.co',
    useCases: ['developers', 'research'],
  },
  {
    id: '20',
    slug: 'vercel',
    name: 'Vercel',
    description: 'Frontend deployment platform with AI features.',
    longDescription: "Vercel is a premier frontend deployment platform optimized for Next.js and other modern frameworks. It offers a seamless development and deployment experience, with integrated AI features to enhance developer productivity and site performance.",
    category: 'Hosting',
    logoUrlId: 'logo-vercel',
    website: 'https://vercel.com',
    useCases: ['developers', 'startups'],
  },
  {
    id: '21',
    slug: 'netlify',
    name: 'Netlify',
    description: 'Web development platform with AI-powered features.',
    longDescription: "Netlify is a powerful web development platform for building and deploying fast, modern websites and applications. It provides a git-based workflow, serverless functions, and a growing suite of AI-powered features to simplify web development.",
    category: 'Hosting',
    logoUrlId: 'logo-netlify',
    website: 'https://www.netlify.com',
    useCases: ['developers', 'startups'],
  },
  {
    id: '22',
    slug: 'runway',
    name: 'Runway',
    description: 'AI-powered video editing and generation tools.',
    longDescription: "Runway offers a suite of powerful AI-powered tools for video and image creation and editing. From text-to-video generation to advanced motion tracking and green screen removal, Runway is a comprehensive platform for creative professionals.",
    category: 'Video',
    logoUrlId: 'logo-runwayml',
    website: 'https://runwayml.com',
    useCases: ['creators', 'video-editors', 'designers'],
  },
  {
    id: '23',
    slug: 'elevenlabs',
    name: 'ElevenLabs',
    description: 'AI voice generation and text-to-speech with realistic voices.',
    longDescription: "ElevenLabs is a leader in AI voice generation, providing incredibly realistic and natural-sounding text-to-speech and voice cloning technology. It's widely used for audiobooks, content creation, and accessibility applications.",
    category: 'Voice',
    logoUrlId: 'logo-elevenlabs',
    website: 'https://elevenlabs.io',
    useCases: ['creators', 'podcasters', 'developers'],
  },
  {
    id: '24',
    slug: 'suno',
    name: 'Suno',
    description: 'AI music generation from text prompts.',
    longDescription: "Suno is an AI music generation tool that creates original songs, complete with vocals and instrumentation, from simple text prompts. It empowers anyone to create radio-quality music in any genre, regardless of their musical ability.",
    category: 'Music',
    trending: true,
    logoUrlId: 'logo-suno',
    website: 'https://www.suno.ai',
    useCases: ['creators', 'musicians', 'developers'],
  },
  {
    id: '25',
    slug: 'udio',
    name: 'Udio',
    description: 'AI music generator with advanced control over song structure and style.',
    longDescription: 'Udio is an advanced AI music creation platform that generates high-quality songs with precise control over genres, moods, and song structure. Created by former Google DeepMind researchers.',
    category: 'Music',
    trending: false,
    logoUrlId: 'logo-udio',
    website: 'https://udio.com',
    useCases: ['creators'],
  },
  {
    id: '26',
    slug: 'mubert',
    name: 'Mubert',
    description: 'AI-generated royalty-free music for content creators and businesses.',
    longDescription: 'Mubert generates unique, royalty-free music in real-time using AI. Perfect for content creators, streamers, podcasters, and businesses needing background music.',
    category: 'Music',
    trending: false,
    logoUrlId: 'logo-mubert',
    website: 'https://mubert.com',
    useCases: ['creators', 'startups'],
  },
  {
    id: '27',
    slug: 'soundraw',
    name: 'Soundraw',
    description: 'AI music generator with customizable tracks for creators.',
    longDescription: 'Soundraw lets you generate unlimited royalty-free music and customize it to fit your content perfectly. Adjust length, tempo, instruments, and energy levels.',
    category: 'Music',
    trending: false,
    logoUrlId: 'logo-soundraw',
    website: 'https://soundraw.io',
    useCases: ['creators'],
  },
  {
    id: '28',
    slug: 'boomy',
    name: 'Boomy',
    description: 'Create songs in seconds and release them to streaming platforms.',
    longDescription: 'Boomy enables anyone to create original songs in seconds and release them on Spotify, Apple Music, and other platforms. Earn royalties from your AI-generated music.',
    category: 'Music',
    trending: false,
    logoUrlId: 'logo-boomy',
    website: 'https://boomy.com',
    useCases: ['creators', 'startups'],
  },
  {
    id: '29',
    slug: 'aiva',
    name: 'AIVA',
    description: 'AI music composition tool for professional soundtracks and scores.',
    longDescription: 'AIVA is an AI composer that creates original music for films, video games, commercials, and other professional projects. Recognized as the first virtual artist by SACEM.',
    category: 'Music',
    trending: false,
    logoUrlId: 'logo-aiva',
    website: 'https://aiva.ai',
    useCases: ['creators', 'developers'],
  },
  {
    id: '30',
    slug: 'beatoven-ai',
    name: 'Beatoven.ai',
    description: 'AI music generator that creates mood-based soundtracks for videos.',
    longDescription: 'Beatoven.ai generates customizable, royalty-free music that adapts to your video\'s mood and pacing. Perfect for content creators and marketers.',
    category: 'Music',
    trending: false,
    logoUrlId: 'logo-beatoven-ai',
    website: 'https://beatoven.ai',
    useCases: ['creators'],
  },
  {
    id: '31',
    slug: 'loudly',
    name: 'Loudly',
    description: 'AI music platform for creating, customizing, and licensing music.',
    longDescription: 'Loudly is an AI-powered music platform that lets you generate, customize, and license original music for commercial use. Features a vast library of sounds and stems.',
    category: 'Music',
    trending: false,
    logoUrlId: 'logo-loudly',
    website: 'https://loudly.com',
    useCases: ['creators', 'startups'],
  },
  {
    id: '32',
    slug: 'splash-pro',
    name: 'Splash Pro',
    description: 'AI music creation with vocals, rap, and singing capabilities.',
    longDescription: 'Splash Pro is an AI music platform that generates songs with vocals, including rap and singing. Create full tracks with lyrics and melodies from text prompts.',
    category: 'Music',
    trending: false,
    logoUrlId: 'logo-splash-pro',
    website: 'https://www.splashmusic.com',
    useCases: ['creators'],
  },
  {
    id: '33',
    slug: 'soundful',
    name: 'Soundful',
    description: 'AI music generator for creators, brands, and artists.',
    longDescription: 'Soundful is an AI music platform that creates unique, royalty-free tracks at the click of a button. Choose from genres, moods, and customize to your needs.',
    category: 'Music',
    trending: false,
    logoUrlId: 'logo-soundful',
    website: 'https://soundful.com',
    useCases: ['creators', 'startups'],
  },
  {
    id: '34',
    slug: 'amper-music',
    name: 'Amper Music',
    description: 'AI music composition integrated with Shutterstock.',
    longDescription: 'Amper Music (now part of Shutterstock) creates custom AI-generated music for content creators. Simple interface for creating professional soundtracks.',
    category: 'Music',
    trending: false,
    logoUrlId: 'logo-amper-music',
    website: 'https://www.shutterstock.com/discover/ampermusic',
    useCases: ['creators'],
  },
  {
    id: '35',
    slug: 'ecrett-music',
    name: 'Ecrett Music',
    description: 'AI music generator for video and game creators.',
    longDescription: 'Ecrett Music generates royalty-free music based on scene, mood, and genre. Perfect for video creators, game developers, and content makers.',
    category: 'Music',
    trending: false,
    logoUrlId: 'logo-ecrett-music',
    website: 'https://ecrettmusic.com',
    useCases: ['creators', 'developers'],
  },
  {
    id: '36',
    slug: 'riffusion',
    name: 'Riffusion',
    description: 'Real-time music generation using stable diffusion.',
    longDescription: 'Riffusion generates music in real-time using stable diffusion. Create unique instrumentals and experiment with different styles and genres.',
    category: 'Music',
    trending: false,
    logoUrlId: 'logo-riffusion',
    website: 'https://riffusion.com',
    useCases: ['developers', 'creators'],
  },
  {
    id: '37',
    slug: 'songburst',
    name: 'Songburst',
    description: 'AI music generator for creating original songs from text descriptions.',
    longDescription: 'Songburst creates original songs from your text prompts. Describe the song you want and get an AI-generated track in seconds.',
    category: 'Music',
    trending: false,
    logoUrlId: 'logo-songburst',
    website: 'https://www.songburst.ai',
    useCases: ['creators'],
  },
  {
    id: '38',
    slug: 'wavtool',
    name: 'WavTool',
    description: 'Browser-based AI music production studio with AI assistance.',
    longDescription: 'WavTool is a browser-based music production tool with AI-powered features for composition, mixing, and mastering. No downloads required.',
    category: 'Music',
    trending: false,
    logoUrlId: 'logo-wavtool',
    website: 'https://wavtool.com',
    useCases: ['creators', 'developers'],
  },
  {
    id: '39',
    slug: 'stable-audio',
    name: 'Stable Audio',
    description: 'High-quality AI audio generation by Stability AI.',
    longDescription: 'Stable Audio by Stability AI generates high-quality music and sound effects from text descriptions. Professional-grade audio for creators and developers.',
    category: 'Audio',
    trending: false,
    logoUrlId: 'logo-stable-audio',
    website: 'https://stableaudio.com',
    useCases: ['creators', 'developers'],
  },
  {
    id: '40',
    slug: 'soundverse',
    name: 'Soundverse',
    description: 'AI music assistant for creators with voice commands.',
    longDescription: 'Soundverse is an AI music assistant that helps you create music using voice commands and text prompts. Generate stems, loops, and full tracks effortlessly.',
    category: 'Music',
    trending: false,
    logoUrlId: 'logo-soundverse',
    website: 'https://soundverse.ai',
    useCases: ['creators', 'developers'],
  },
  {
    id: '41',
    slug: 'harmonai',
    name: 'Harmonai',
    description: 'Open-source AI music generation community and tools.',
    longDescription: 'Harmonai is a community-driven organization releasing open-source generative audio tools. Create music with cutting-edge AI models available to everyone.',
    category: 'Music',
    trending: false,
    logoUrlId: 'logo-harmonai',
    website: 'https://www.harmonai.org',
    useCases: ['developers'],
  },
  {
    id: '42',
    slug: 'amadeus-code',
    name: 'Amadeus Code',
    description: 'AI songwriting assistant powered by hit songs.',
    longDescription: 'Amadeus Code uses AI trained on hit songs to help you create melodies and chord progressions. Perfect for songwriters seeking inspiration.',
    category: 'Music',
    trending: false,
    logoUrlId: 'logo-amadeus-code',
    website: 'https://amadeuscode.com/',
    useCases: ['creators'],
  },
  {
    id: '43',
    slug: 'musicfy',
    name: 'Musicfy',
    description: 'AI voice cloning and music generation platform.',
    longDescription: 'Musicfy lets you create AI voice clones and generate music covers with any voice. Clone your voice or use celebrity voices for your tracks.',
    category: 'Voice',
    trending: false,
    logoUrlId: 'logo-musicfy',
    website: 'https://musicfy.lol',
    useCases: ['creators'],
  },
  {
    id: '44',
    slug: 'synthesia',
    name: 'Synthesia',
    description: 'AI video generation with realistic avatars and voiceovers',
    longDescription: 'Synthesia creates professional videos with AI avatars in 120+ languages. Transform text into engaging video presentations without cameras or actors.',
    category: 'Video',
    logoUrlId: 'logo-synthesia',
    website: 'https://www.synthesia.io',
    useCases: ['creators', 'startups'],
  },
  {
    id: '45',
    slug: 'heygen',
    name: 'HeyGen',
    description: 'AI video generator with customizable avatars and voice cloning',
    longDescription: 'HeyGen lets you create studio-quality videos with AI avatars, voice cloning, and automatic translations. Perfect for marketing, training, and social media.',
    category: 'Video',
    logoUrlId: 'logo-heygen',
    website: 'https://www.heygen.com',
    useCases: ['creators', 'startups'],
  },
  {
    id: '46',
    slug: 'pictory',
    name: 'Pictory',
    description: 'Turn scripts and articles into engaging videos automatically',
    longDescription: 'Pictory converts long-form content into short, branded videos perfect for social media. Automatically extract highlights from Zoom recordings and webinars.',
    category: 'Video',
    logoUrlId: 'logo-pictory',
    website: 'https://pictory.ai',
    useCases: ['creators', 'startups'],
  },
  {
    id: '47',
    slug: 'invideo-ai',
    name: 'Invideo AI',
    description: 'AI video creator that turns text prompts into complete videos',
    longDescription: 'Invideo AI generates complete videos from simple text prompts. Create YouTube videos, social media content, and ads with AI-powered editing and scripting.',
    category: 'Video',
    logoUrlId: 'logo-invideo-ai',
    website: 'https://invideo.io',
    useCases: ['creators', 'startups'],
  },
  {
    id: '48',
    slug: 'pika',
    name: 'Pika',
    description: 'AI video generator that creates and edits videos from text',
    longDescription: 'Pika is an AI video platform that generates videos from text descriptions and images. Modify videos with simple text commands for creative control.',
    category: 'Video',
    logoUrlId: 'logo-pika',
    website: 'https://pika.art',
    useCases: ['creators'],
  },
  {
    id: '49',
    slug: 'luma-dream-machine',
    name: 'Luma Dream Machine',
    description: 'High-quality AI video generation from text and images',
    longDescription: 'Luma Dream Machine creates cinematic, high-quality videos from text prompts and images. Known for realistic motion and smooth transitions.',
    category: 'Video',
    logoUrlId: 'logo-luma-dream-machine',
    website: 'https://lumalabs.ai',
    useCases: ['creators'],
  },
  {
    id: '50',
    slug: 'kling-ai',
    name: 'Kling AI',
    description: 'Advanced AI video generation with long-duration support',
    longDescription: 'Kling AI generates high-quality videos up to 2 minutes long with realistic physics and motion. Create stunning visuals from text descriptions.',
    category: 'Video',
    logoUrlId: 'logo-kling-ai',
    website: 'https://klingai.com',
    useCases: ['creators'],
  },
  {
    id: '51',
    slug: 'fliki',
    name: 'Fliki',
    description: 'Text-to-video and text-to-speech for content creators',
    longDescription: 'Fliki converts text into videos with realistic voiceovers in minutes. Create social media content, product demos, and educational videos effortlessly.',
    category: 'Video',
    logoUrlId: 'logo-fliki',
    website: 'https://fliki.ai',
    useCases: ['creators'],
  },
  {
    id: '52',
    slug: 'colossyan',
    name: 'Colossyan',
    description: 'AI video platform for workplace learning and training',
    longDescription: 'Colossyan creates professional training videos with AI avatars and automatic translations. Perfect for corporate learning and employee onboarding.',
    category: 'Video',
    logoUrlId: 'logo-colossyan',
    website: 'https://www.colossyan.com',
    useCases: ['startups'],
  },
  {
    id: '53',
    slug: 'elai-io',
    name: 'Elai.io',
    description: 'AI video generator for training and explainer videos',
    longDescription: 'Elai.io creates professional videos from text with AI presenters. Ideal for training content, explainer videos, and educational material.',
    category: 'Video',
    logoUrlId: 'logo-elai-io',
    website: 'https://elai.io',
    useCases: ['startups', 'students'],
  },
  {
    id: '54',
    slug: 'steve-ai',
    name: 'Steve.AI',
    description: 'AI video maker for animations and live-action videos',
    longDescription: 'Steve.AI creates animated and live-action videos from scripts. Choose from various styles including cartoon, 2D/3D animation, and live video.',
    category: 'Video',
    logoUrlId: 'logo-steve-ai',
    website: 'https://steve.ai',
    useCases: ['creators'],
  },
  {
    id: '55',
    slug: 'deepbrain-ai',
    name: 'Deepbrain AI',
    description: 'Hyper-realistic AI avatar video generation platform',
    longDescription: 'Deepbrain AI (AI Studios) creates videos with hyper-realistic AI avatars. Generate professional video content in multiple languages with natural gestures.',
    category: 'Video',
    logoUrlId: 'logo-deepbrain-ai',
    website: 'https://www.deepbrain.io',
    useCases: ['startups'],
  },
  {
    id: '57',
    slug: 'moonvalley',
    name: 'Moonvalley',
    description: 'AI video generation with artistic styles and control',
    longDescription: 'Moonvalley creates stunning videos from text with various artistic styles. Generate cinematic, animated, or realistic videos with style control.',
    category: 'Video',
    logoUrlId: 'logo-moonvalley',
    website: 'https://moonvalley.ai',
    useCases: ['creators'],
  },
  {
    id: '58',
    slug: 'artflow-ai',
    name: 'Artflow AI',
    description: 'Create animated videos with consistent AI characters',
    longDescription: 'Artflow AI lets you create videos with consistent AI-generated characters. Design your characters and animate them in various scenes and scenarios.',
    category: 'Video',
    logoUrlId: 'logo-artflow-ai',
    website: 'https://artflow.ai',
    useCases: ['creators'],
  },
  {
    id: '59',
    slug: 'opusclip',
    name: 'OpusClip',
    description: 'AI-powered video clipping for social media shorts',
    longDescription: 'OpusClip automatically identifies viral-worthy moments in long videos and creates short clips perfect for TikTok, YouTube Shorts, and Instagram Reels.',
    category: 'Video',
    logoUrlId: 'logo-opusclip',
    website: 'https://www.opus.pro',
    useCases: ['creators'],
  },
  {
    id: '60',
    slug: 'vidyo-ai',
    name: 'Vidyo.ai',
    description: 'Repurpose long videos into social media shorts with AI',
    longDescription: 'Vidyo.ai automatically turns long-form videos into short, engaging clips for social media. AI identifies the best moments and adds captions automatically.',
    category: 'Video',
    logoUrlId: 'logo-vidyo-ai',
    website: 'https://vidyo.ai',
    useCases: ['creators'],
  },
  {
    id: '61',
    slug: 'kapwing',
    name: 'Kapwing',
    description: 'Collaborative online video editor with AI features',
    longDescription: 'Kapwing is an online video editor with AI-powered tools for subtitles, resizing, background removal, and more. Perfect for teams and content creators.',
    category: 'Video',
    logoUrlId: 'logo-kapwing',
    website: 'https://www.kapwing.com',
    useCases: ['creators', 'startups'],
  },
  {
    id: '62',
    slug: 'animoto',
    name: 'Animoto',
    description: 'AI video maker for marketing and social media',
    longDescription: 'Animoto creates professional marketing videos with AI assistance. Drag-and-drop editor with templates for social media, ads, and presentations.',
    category: 'Video',
    logoUrlId: 'logo-animoto',
    website: 'https://animoto.com',
    useCases: ['creators'],
  },
  {
    id: '63',
    slug: 'clipchamp',
    name: 'Clipchamp',
    description: "Microsoft's AI-powered video editor for everyone",
    longDescription: "Clipchamp (by Microsoft) offers easy video editing with AI features like auto-captions, text-to-speech, and templates. Built into Windows 11.",
    category: 'Video',
    logoUrlId: 'logo-clipchamp',
    website: 'https://clipchamp.com',
    useCases: ['creators'],
  },
  {
    id: '64',
    slug: 'captions-app',
    name: 'Captions',
    description: 'AI-powered video editing and captioning for creators',
    longDescription: 'Captions automatically adds animated captions to your videos, corrects eye contact with AI, and enhances video quality. Perfect for social media creators.',
    category: 'Video',
    logoUrlId: 'logo-captions-app',
    website: 'https://www.captions.ai',
    useCases: ['creators'],
  },
  {
    id: '65',
    slug: 'kaiber',
    name: 'Kaiber',
    description: 'Transform videos and images with AI artistic styles',
    longDescription: 'Kaiber transforms your videos and images into artistic animations. Apply different visual styles to create unique music videos and artistic content.',
    category: 'Video',
    logoUrlId: 'logo-kaiber',
    website: 'https://kaiber.ai',
    useCases: ['creators'],
  },
  {
    id: '66',
    slug: 'wonder-studio',
    name: 'Wonder Studio',
    description: 'AI tool for adding CG characters to live-action footage',
    longDescription: 'Wonder Studio automatically animates, lights, and composes CG characters into live-action scenes. Revolutionary tool for filmmakers and VFX artists.',
    category: 'Video',
    logoUrlId: 'logo-wonder-studio',
    website: 'https://wonderdynamics.com',
    useCases: ['creators', 'developers'],
  },
  {
    id: '67',
    slug: 'd-id',
    name: 'D-ID',
    description: 'AI video platform with talking avatars and face animation',
    longDescription: 'D-ID creates videos with talking avatars from still images. Generate personalized video content with AI-powered facial animation and voice.',
    category: 'Video',
    logoUrlId: 'logo-d-id',
    website: 'https://www.d-id.com',
    useCases: ['creators'],
  },
  {
    id: '68',
    slug: 'lumen5',
    name: 'Lumen5',
    description: 'AI video creator that transforms blog posts into videos',
    longDescription: 'Lumen5 automatically converts blog posts and articles into engaging videos. AI selects relevant media and creates professional social media content.',
    category: 'Video',
    logoUrlId: 'logo-lumen5',
    website: 'https://lumen5.com',
    useCases: ['creators'],
  }
];


const articles: Article[] = [
  {
    id: '1',
    slug: 'ai-girlfriend-companionship-digital-age',
    title: 'The Rise of AI Girlfriends: Companionship in the Digital Age',
    excerpt: 'Exploring the fast-growing world of AI companions. What\'s the appeal, what\'s the tech, and what are the ethical questions we need to ask?',
    date: '2024-07-20',
    author: 'AI Tools Korner Staff',
    imageUrlId: 'article-image-1',
    content: article1Content,
  },
  {
    id: '2',
    slug: 'ai-video-revolution-sora-pika-runway',
    title: 'Sora, Pika, Runway: The AI Video Revolution is Here',
    excerpt: 'From OpenAI\'s Sora to competitors like Pika and Runway, text-to-video AI is changing filmmaking and content creation forever. How does it work and what\'s next?',
    date: '2024-07-18',
    author: 'Alex Ray',
    imageUrlId: 'article-image-2',
    content: article2Content,
  },
  {
    id: '3',
    slug: 'ai-agents-autonomous-workforce',
    title: 'Forget AI Tools, Meet Your New AI Agent',
    excerpt: 'The next evolution of AI is here: autonomous agents that can complete complex tasks on their own. Are they the future of productivity or a threat to jobs?',
    date: '2024-07-16',
    author: 'Jane Doe',
    imageUrlId: 'article-image-3',
    content: article3Content,
  }
];

export function getTools(): Tool[] {
  const orderedTools = [
    'suno', 'udio', 'mubert', 'stable-audio', 'soundraw', 'aiva', 'beatoven-ai', 'soundverse', 'musicfy', 'boomy', 'loudly', 'soundful', 'splash-pro', 'wavtool', 'amadeus-code', 'harmonai', 'riffusion', 'ecrett-music', 'songburst', 'amper-music'
  ];
  
  const sortedMusicTools = tools
    .filter(t => orderedTools.includes(t.slug))
    .sort((a, b) => orderedTools.indexOf(a.slug) - orderedTools.indexOf(b.slug));

  const otherTools = tools.filter(t => !orderedTools.includes(t.slug));

  return [...sortedMusicTools, ...otherTools];
}

export function getArticles(): Article[] {
  return articles;
}

export function getToolBySlug(slug: string): Tool | undefined {
  return tools.find((tool) => tool.slug === slug);
}

export function getArticleBySlug(slug: string): Article | undefined {
  return articles.find((article) => article.slug === slug);
}

export function getTrendingTools(): Tool[] {
  return tools.filter((tool) => tool.trending);
}

export function getLatestArticles(count: number): Article[] {
  return [...articles]
    .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime())
    .slice(0, count);
}

export function getAllCategories(): Category[] {
  return CATEGORIES;
}

export function getCategoryBySlug(slug: string): Category | undefined {
  return CATEGORIES.find((cat) => cat.slug === slug);
}

export function getToolsByCategory(category: ToolCategory): Tool[] {
  return tools.filter((tool) => tool.category === category);
}

export function getAllUseCases(): UseCase[] {
  return USE_CASES;
}

export function getUseCaseBySlug(slug: string): UseCase | undefined {
  return USE_CASES.find((uc) => uc.slug === slug);
}

export function getToolsByUseCase(useCaseSlug: string): Tool[] {
  return tools.filter((tool) => tool.useCases?.includes(useCaseSlug));
}
